# Movie Recommendation Project

## Data Exploration

In [46]:
import pandas as pd
from pprint import PrettyPrinter

In [47]:
pp = PrettyPrinter(indent=4)

## Loading the Data

In [48]:
#Checking if I have the files I need in my folder
!ls -l 'tmdb_5000_movies.csv' 'tmdb_5000_credits.csv'

-rw-r--r--@ 1 subhantariq  staff  40044293 Mar  1 22:41 tmdb_5000_credits.csv
-rw-r--r--@ 1 subhantariq  staff   5722964 Aug 31  2025 tmdb_5000_movies.csv

In [49]:
# Load data files
movies_df_all = pd.read_csv('tmdb_5000_movies.csv')
credits_df_all = pd.read_csv('tmdb_5000_credits.csv')

## Exploring the Data

In [50]:
movies_df_all.shape

(4803, 20)

In [51]:
movies_df_all.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""name"": ""Fantasy""}, {""id"": 878, ""name"": ""Science Fiction""}]",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"": 2964, ""name"": ""future""}, {""id"": 3386, ""name"": ""space war""}, {""id"": 3388, ""name"": ""space colony""}, {""id"": 3679, ""name"": ""society""}, {""id"": 3801, ""name"": ""space travel""}, {""id"": 9685, ""name"": ""futuristic""}, {""id"": 9840, ""name"": ""romance""}, {""id"": 9882, ""name"": ""space""}, {""id"": 9951, ""name"": ""alien""}, {""id"": 10148, ""name"": ""tribe""}, {""id"": 10158, ""name"": ""alien planet""}, {""id"": 10987, ""name"": ""cgi""}, {""id"": 11399, ""name"": ""marine""}, {""id"": 13065, ""name"": ""soldier""}, {""id"": 14643, ""name"": ""battle""}, {""id"": 14720, ""name"": ""love affair""}, {""id"": 165431, ""name"": ""anti war""}, {""id"": 193554, ""name"": ""power relations""}, {""id"": 206690, ""name"": ""mind and soul""}, {""id"": 209714, ""name"": ""3d""}]",en,Avatar,"In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289}, {""name"": ""Twentieth Century Fox Film Corporation"", ""id"": 306}, {""name"": ""Dune Entertainment"", ""id"": 444}, {""name"": ""Lightstorm Entertainment"", ""id"": 574}]","[{""iso_3166_1"": ""US"", ""name"": ""United States of America""}, {""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""}]",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}]",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""name"": ""Action""}]",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""name"": ""drug abuse""}, {""id"": 911, ""name"": ""exotic island""}, {""id"": 1319, ""name"": ""east india trading company""}, {""id"": 2038, ""name"": ""love of one's life""}, {""id"": 2052, ""name"": ""traitor""}, {""id"": 2580, ""name"": ""shipwreck""}, {""id"": 2660, ""name"": ""strong woman""}, {""id"": 3799, ""name"": ""ship""}, {""id"": 5740, ""name"": ""alliance""}, {""id"": 5941, ""name"": ""calypso""}, {""id"": 6155, ""name"": ""afterlife""}, {""id"": 6211, ""name"": ""fighter""}, {""id"": 12988, ""name"": ""pirate""}, {""id"": 157186, ""name"": ""swashbuckler""}, {""id"": 179430, ""name"": ""aftercreditsstinger""}]",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems.",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""name"": ""Jerry Bruckheimer Films"", ""id"": 130}, {""name"": ""Second Mate Productions"", ""id"": 19936}]","[{""iso_3166_1"": ""US"", ""name"": ""United States of America""}]",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""name"": ""Adventure""}, {""id"": 80, ""name"": ""Crime""}]",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name"": ""based on novel""}, {""id"": 4289, ""name"": ""secret agent""}, {""id"": 9663, ""name"": ""sequel""}, {""id"": 14555, ""name"": ""mi6""}, {""id"": 156095, ""name"": ""british secret service""}, {""id"": 158431, ""name"": ""united kingdom""}]",en,Spectre,"A cryptic message from Bond’s past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE.",107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""name"": ""Danjaq"", ""id"": 10761}, {""name"": ""B24"", ""id"": 69434}]","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""}, {""iso_3166_1"": ""US"", ""name"": ""United States of America""}]",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""}, {""iso_639_1"": ""en"", ""name"": ""English""}, {""iso_639_1"": ""es"", ""name"": ""Espa\u00f1ol""}, {""iso_639_1"": ""it"", ""name"": ""Italiano""}, {""iso_639_1"": ""de"", ""name"": ""Deutsch""}]",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name"": ""Drama""}, {""id"": 53, ""name"": ""Thriller""}]",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853, ""name"": ""crime fighter""}, {""id"": 949, ""name"": ""terrorist""}, {""id"": 1308, ""name"": ""secret identity""}, {""id"": 1437, ""name"": ""burglar""}, {""id"": 3051, ""name"": ""hostage drama""}, {""id"": 3562, ""name"": ""time bomb""}, {""id"": 6969, ""name"": ""gotham city""}, {""id"": 7002, ""name"": ""vigilante""}, {""id"": 9665, ""name"": ""cover-up""}, {""id"": 9715, ""name"": ""superhero""}, {""id"": 9990, ""name"": ""villainess""}, {""id"": 10044, ""name"": ""tragic hero""}, {""id"": 13015, ""name"": ""terrorism""}, {""id"": 14796, ""name"": ""destruction""}, {""id"": 18933, ""name"": ""catwoman""}, {""id"": 156082, ""name"": ""cat burglar""}, {""id"": 156395, ""name"": ""imax""}, {""id"": 173272, ""name"": ""flood""}, {""id"": 179093, ""name"": ""criminal underworld""}, {""id"": 230775, ""name"": ""batman""}]",en,The Dark Knight Rises,"Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.",112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""name"": ""Warner Bros."", ""id"": 6194}, {""name"": ""DC Entertainment"", ""id"": 9993}, {""name"": ""Syncopy"", ""id"": 9996}]","[{""iso_3166_1"": ""US"", ""name"": ""United States of America""}]",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""name"": ""Adventure""}, {""id"": 878, ""name"": ""Science Fiction""}]",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"": 839, ""name"": ""mars""}, {""id"": 1456, ""name"": ""medallion""}, {""id"": 3801, ""name"": ""space travel""}, {""id"": 7376, ""name"": ""princess""}, {""id"": 9951, ""name"": ""alien""}, {""id"": 10028, ""name"": ""steampunk""}, {""id"": 10539, ""name"": ""martian""}, {""id"": 10685, ""name"": ""escape""}, {""id"": 161511, ""name"": ""edgar rice burroughs""}, {""id"": 163252, ""name"": ""alien race""}, {""id"": 179102, ""name"": ""superhuman strength""}, {""id"": 190320, ""name"": ""mars civilization""}, {""id"": 195446, ""name"": ""sword and planet""}, {""id"": 207928, ""name"": ""19th century""}, {""id"": 209714, ""name"": ""3d""}]",en,John Carter,"John Carter is a war-weary, former military captain who's inexplicably transported to the mysterious and exotic planet of Barsoom (Mars) and reluctantly becomes embroiled in an epic conflict. It's a world on the brink of collapse, and Carter rediscovers his humanity when he realizes the survival of Barsoom and its people rests in his hands.",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States of America""}]",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [52]:
movies_df_all.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [53]:
#Now we will explore the other datafile (credits file)
credits_df_all.shape

(4803, 4)

In [54]:
credits_df_all.head()

   movie_id                                     title  \
0     19995                                    Avatar
1       285  Pirates of the Caribbean: At World's End
2    206647                                   Spectre
3     49026                     The Dark Knight Rises
4     49529                               John Carter


In [55]:
credits_df_all.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

## Feature Selection

In [56]:
movies_df = movies_df_all[['title','overview','genres','keywords','production_companies',\
                           'release_date','original_language']]

In [57]:
movies_df.shape

(4803, 7)

In [58]:
movies_df.head()

,title,overview,genres,keywords,production_companies,release_date,original_language
0,Avatar,"In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""name"": ""Fantasy""}, {""id"": 878, ""name"": ""Science Fiction""}]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"": 2964, ""name"": ""future""}, {""id"": 3386, ""name"": ""space war""}, {""id"": 3388, ""name"": ""space colony""}, {""id"": 3679, ""name"": ""society""}, {""id"": 3801, ""name"": ""space travel""}, {""id"": 9685, ""name"": ""futuristic""}, {""id"": 9840, ""name"": ""romance""}, {""id"": 9882, ""name"": ""space""}, {""id"": 9951, ""name"": ""alien""}, {""id"": 10148, ""name"": ""tribe""}, {""id"": 10158, ""name"": ""alien planet""}, {""id"": 10987, ""name"": ""cgi""}, {""id"": 11399, ""name"": ""marine""}, {""id"": 13065, ""name"": ""soldier""}, {""id"": 14643, ""name"": ""battle""}, {""id"": 14720, ""name"": ""love affair""}, {""id"": 165431, ""name"": ""anti war""}, {""id"": 193554, ""name"": ""power relations""}, {""id"": 206690, ""name"": ""mind and soul""}, {""id"": 209714, ""name"": ""3d""}]","[{""name"": ""Ingenious Film Partners"", ""id"": 289}, {""name"": ""Twentieth Century Fox Film Corporation"", ""id"": 306}, {""name"": ""Dune Entertainment"", ""id"": 444}, {""name"": ""Lightstorm Entertainment"", ""id"": 574}]",2009-12-10,en
1,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, has come back to life and is headed to the edge of the Earth with Will Turner and Elizabeth Swann. But nothing is quite as it seems.","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""name"": ""Action""}]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""name"": ""drug abuse""}, {""id"": 911, ""name"": ""exotic island""}, {""id"": 1319, ""name"": ""east india trading company""}, {""id"": 2038, ""name"": ""love of one's life""}, {""id"": 2052, ""name"": ""traitor""}, {""id"": 2580, ""name"": ""shipwreck""}, {""id"": 2660, ""name"": ""strong woman""}, {""id"": 3799, ""name"": ""ship""}, {""id"": 5740, ""name"": ""alliance""}, {""id"": 5941, ""name"": ""calypso""}, {""id"": 6155, ""name"": ""afterlife""}, {""id"": 6211, ""name"": ""fighter""}, {""id"": 12988, ""name"": ""pirate""}, {""id"": 157186, ""name"": ""swashbuckler""}, {""id"": 179430, ""name"": ""aftercreditsstinger""}]","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""name"": ""Jerry Bruckheimer Films"", ""id"": 130}, {""name"": ""Second Mate Productions"", ""id"": 19936}]",2007-05-19,en
2,Spectre,"A cryptic message from Bond’s past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE.","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""name"": ""Adventure""}, {""id"": 80, ""name"": ""Crime""}]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name"": ""based on novel""}, {""id"": 4289, ""name"": ""secret agent""}, {""id"": 9663, ""name"": ""sequel""}, {""id"": 14555, ""name"": ""mi6""}, {""id"": 156095, ""name"": ""british secret service""}, {""id"": 158431, ""name"": ""united kingdom""}]","[{""name"": ""Columbia Pictures"", ""id"": 5}, {""name"": ""Danjaq"", ""id"": 10761}, {""name"": ""B24"", ""id"": 69434}]",2015-10-26,en
3,The Dark Knight Rises,"Following the death of District Attorney Harvey Dent, Batman assumes responsibility for Dent's crimes to protect the late attorney's reputation and is subsequently hunted by the Gotham City Police Department. Eight years later, Batman encounters the mysterious Selina Kyle and the villainous Bane, a new terrorist leader who overwhelms Gotham's finest. The Dark Knight resurfaces to protect a city that has branded him an enemy.","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name"": ""Drama""}, {""id"": 53, ""name"": ""Thriller""}]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853, ""name"": ""crime fighter""}, {""id"": 949, ""name"": ""terrorist""}, {""id"": 1308, ""name"": ""secret identity""}, {""id"": 1437, ""name"": ""burglar""}, {""id"": 3051, ""name"": ""hostage drama""}, {""id"": 3562, ""name"": ""time bomb""}, {""id"": 6969, ""name"": ""gotham city""}, {""id"": 7002, ""name"": ""vigilante""}, {""id"": 9665, ""name"": ""cover-up""}, {""id"": 9715, ""name"": ""superhero""}, {""id"": 9990, ""name"": ""villainess""}, {""id"": 10044, ""name"": ""tragic hero""}, {""id"": 13015, ""name"": ""terrorism""}, {""id"": 14796, ""name"": ""destruction""}, {""id"": 18933, ""name"": ""catwoman""}, {""id"": 156082, ""name"": ""cat burglar""}, {""id"": 156395, ""name"": ""imax""}, {""id"": 173272, ""name"": ""flood""}, {""id"": 179093, ""name"": ""criminal underworld""}, {""id"": 230775, ""name"": ""batman""}]","[{""name"": ""Legendary Pictures"", ""id"": 923}, {""name"": ""Warner Bros."", ""id"": 6194}, {""name"": ""DC Entertainment"", ""id"": 9993}, {""name"": ""Syncopy"", ""id"": 9996}]",2012-07-16,en
4,John Carter,"John Carter is a war-weary, former military captain who's inexplicably transported to the mysterious and exotic planet of Barsoom (Mars) and reluctantly becomes embroiled in an epic conflict. It's a world on the brink of collapse, and Carter rediscovers his humanity when he realizes the survival of Barsoom and its people rests in his hands.","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""name"": ""Adventure""}, {""id"": 878, ""name"": ""Science Fiction""}]","[{""id"": 818, ""name"": ""based on novel""}, {""id"": 839, ""name"": ""mars""}, {""id"": 1456, ""name"": ""medallion""}, {""id"": 3801, ""name"": ""space travel""}, {""id"": 7376, ""name"": ""princess""}, {""id"": 9951, ""name"": ""alien""}, {""id"": 10028, ""name"": ""steampunk""}, {""id"": 10539, ""name"": ""martian""}, {""id"": 10685, ""name"": ""escape""}, {""id"": 161511, ""name"": ""edgar rice burroughs""}, {""id"": 163252, ""name"": ""alien race""}, {""id"": 179102, ""name"": ""superhuman strength""}, {""id"": 190320, ""name"": ""mars civilization""}, {""id"": 195446, ""name"": ""sword and planet""}, {""id"": 207928, ""name"": ""19th century""}, {""id"": 209714, ""name"": ""3d""}]","[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",2012-03-07,en

In [59]:
credits_df = credits_df_all[['title','cast','crew']]

In [60]:
credits_df.head()

                                      title  \
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter


## Preprocessing

In [61]:
# Checking for Missing Values in movies data
movies_df.isnull().sum()
# Note: overview has 31 missing values, release_date has 1 missing value

title                    0
overview                31
genres                   0
keywords                 0
production_companies     0
release_date             1
original_language        0
dtype: int64

In [62]:
# Displaying rows where overview is null
movies_df[movies_df['overview'].isnull()]

,title,overview,genres,keywords,production_companies,release_date,original_language
65,The Dark Knight,NaN,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 28, ""name"": ""Action""}, {""id"": 80, ""name"": ""Crime""}, {""id"": 53, ""name"": ""Thriller""}]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853, ""name"": ""crime fighter""}, {""id"": 1308, ""name"": ""secret identity""}, {""id"": 3151, ""name"": ""scarecrow""}, {""id"": 4426, ""name"": ""sadism""}, {""id"": 4630, ""name"": ""chaos""}, {""id"": 6969, ""name"": ""gotham city""}, {""id"": 7002, ""name"": ""vigilante""}, {""id"": 9537, ""name"": ""joker""}, {""id"": 9715, ""name"": ""superhero""}, {""id"": 9717, ""name"": ""based on comic book""}, {""id"": 10044, ""name"": ""tragic hero""}, {""id"": 10291, ""name"": ""organized crime""}, {""id"": 18023, ""name"": ""criminal mastermind""}, {""id"": 33518, ""name"": ""district attorney""}, {""id"": 156395, ""name"": ""imax""}, {""id"": 163074, ""name"": ""super villain""}, {""id"": 163455, ""name"": ""super powers""}, {""id"": 230775, ""name"": ""batman""}]","[{""name"": ""DC Comics"", ""id"": 429}, {""name"": ""Legendary Pictures"", ""id"": 923}, {""name"": ""Warner Bros."", ""id"": 6194}, {""name"": ""DC Entertainment"", ""id"": 9993}, {""name"": ""Syncopy"", ""id"": 9996}]",2008-07-16,en
77,Inside Out,NaN,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 35, ""name"": ""Comedy""}, {""id"": 16, ""name"": ""Animation""}, {""id"": 10751, ""name"": ""Family""}]","[{""id"": 1566, ""name"": ""dream""}, {""id"": 6513, ""name"": ""cartoon""}, {""id"": 7942, ""name"": ""imaginary friend""}, {""id"": 10336, ""name"": ""animation""}, {""id"": 18035, ""name"": ""family""}, {""id"": 18253, ""name"": ""moving""}, {""id"": 161155, ""name"": ""kids""}, {""id"": 163227, ""name"": ""unicorn""}, {""id"": 179431, ""name"": ""duringcreditsstinger""}, {""id"": 209714, ""name"": ""3d""}, {""id"": 211269, ""name"": ""emotions""}]","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""name"": ""Pixar Animation Studios"", ""id"": 3}]",2015-06-09,en
94,Guardians of the Galaxy,NaN,"[{""id"": 28, ""name"": ""Action""}, {""id"": 878, ""name"": ""Science Fiction""}, {""id"": 12, ""name"": ""Adventure""}]","[{""id"": 8828, ""name"": ""marvel comic""}, {""id"": 9831, ""name"": ""spaceship""}, {""id"": 9882, ""name"": ""space""}, {""id"": 12405, ""name"": ""outer space""}, {""id"": 13014, ""name"": ""orphan""}, {""id"": 175428, ""name"": ""adventurer""}, {""id"": 179430, ""name"": ""aftercreditsstinger""}, {""id"": 179431, ""name"": ""duringcreditsstinger""}, {""id"": 180547, ""name"": ""marvel cinematic universe""}]","[{""name"": ""Marvel Studios"", ""id"": 420}, {""name"": ""Moving Picture Company (MPC)"", ""id"": 20478}, {""name"": ""Bulletproof Cupid"", ""id"": 54850}, {""name"": ""Revolution Sun Studios"", ""id"": 76043}]",2014-07-30,en
95,Interstellar,NaN,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 18, ""name"": ""Drama""}, {""id"": 878, ""name"": ""Science Fiction""}]","[{""id"": 83, ""name"": ""saving the world""}, {""id"": 310, ""name"": ""artificial intelligence""}, {""id"": 494, ""name"": ""father son relationship""}, {""id"": 641, ""name"": ""single parent""}, {""id"": 1432, ""name"": ""nasa""}, {""id"": 1963, ""name"": ""expedition""}, {""id"": 3417, ""name"": ""wormhole""}, {""id"": 3801, ""name"": ""space travel""}, {""id"": 4337, ""name"": ""famine""}, {""id"": 4380, ""name"": ""black hole""}, {""id"": 4565, ""name"": ""dystopia""}, {""id"": 4776, ""name"": ""race against time""}, {""id"": 8056, ""name"": ""quantum mechanics""}, {""id"": 9831, ""name"": ""spaceship""}, {""id"": 9882, ""name"": ""space""}, {""id"": 10084, ""name"": ""rescue""}, {""id"": 10235, ""name"": ""family relationships""}, {""id"": 13127, ""name"": ""farmhouse""}, {""id"": 14544, ""name"": ""robot""}, {""id"": 14626, ""name"": ""astronaut""}, {""id"": 14760, ""name"": ""scientist""}, {""id"": 15300, ""name"": ""father daughter relationship""}, {""id"": 33479, ""name"": ""single father""}, {""id"": 154846, ""name"": ""farmer""}, {""id"": 156039, ""name"": ""space station""}, {""id"": 156395, ""name"": ""imax""}, {""id"": 160331, ""name"": ""astrophysics""}, {""id"": 162630, ""name"": ""zero gravity""}, {""id"": 189098, ""name"": ""courage""}, {""id"": 208757, ""name"": ""time paradox""}, {""id"": 214349, ""name"": ""relativity""}]","[{""name"": ""Paramount Pictures"", ""id"": 4}, {""name"": ""Legendary Pictures"", ""id"": 923}, {""name"": ""Warner Bros."", ""id"": 6194}, {""name"": ""Syncopy"", ""id"": 9996}, {""name"": ""Lynda Obst Productions"", ""id"": 13769}]",2014-11-05,en
96,Inception,NaN,"[{""id"": 28, ""name"": ""Action""}, {""id"": 53, ""name"": ""Thriller""}, {""id"": 878, ""name"": ""Science Fiction""}, {""id"": 9648, ""name"": ""Mystery""}, {""id"": 12, ""name"": ""Adventure""}]","[{""id"": 1014, ""name"": ""loss of lover""}, {""id"": 1566, ""name"": ""dream""}, {""id"": 1930, ""name"": ""kidnapping""}, {""id"": 2116, ""name"": ""sleep""}, {""id"": 2117, ""name"": ""subconsciousness""}, {""id"": 10051, ""name"": ""heist""}, {""id"": 11436, ""name"": ""redemption""}, {""id"": 160137, ""name"": ""female hero""}]","[{""name"": ""Legendary Pictures"", ""id"": 923}, {""name"": ""Warner Bros."", ""id"": 6194}, {""name"": ""Syncopy"", ""id"": 9996}]",2010-07-14,en
262,The Lord of the Rings: The Fellowship of the Ring,NaN,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""name"": ""Action""}]","[{""id"": 603, ""name"": ""elves""}, {""id"": 604, ""name"": ""dwarves""}, {""id"": 606, ""name"": ""orcs""}, {""id"": 609, ""name"": ""middle-earth (tolkien)""}, {""id"": 611, ""name"": ""hobbit""}, {""id"": 818, ""name"": ""based on novel""}, {""id"": 1262, ""name"": ""mountains""}, {""id"": 2407, ""name"": ""fireworks""}, {""id"": 3098, ""name"": ""castle""}, {""id"": 3347, ""name"": ""volcano""}, {""id"": 4587, ""name"": ""password""}, {""id"": 4959, ""name"": ""death of a friend""}, {""id"": 6464, ""name"": ""uncle""}, {""id"": 46951, ""name"": ""mirror""}, {""id"": 177912, ""name"": ""wizard""}, {""id"": 234213, ""name"": ""sword and sorcery""}]","[{""name"": ""WingNut Films"", ""id"": 11}, {""name"": ""New Line Cinema"", ""id"": 12}, {""name"": ""The Saul Zaentz Company"", ""id"": 5237}]",2001-12-18,en
287,Django Unchained,NaN,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 37, ""name"": ""Western""}]","[{""id"": 801, ""name"": ""bounty hunter""}, {""id"": 1701, ""name"": ""hero""}, {""id"": 3136, ""name"": ""plantation""}, {""id"": 3679, ""name"": ""society""}, {""id"": 6054, ""name"": ""friendship""}, {""id"": 9713, ""name"": ""friends""}, {""id"": 9748, ""name"": ""revenge""}, {""id"": 9823, ""name"": ""rivalry""}, {""id"": 10084, ""name"": ""rescue""}, {""id"": 10950, ""name"": ""shootout""}, {""id"": 12425, ""name"": ""racism""}, {""id"": 15017, ""name"": ""danger""}, {""id"": 33780, ""name"": ""dentist""}, {""id"": 160324, ""name"": ""django""}, {""id"": 163129, ""name"": ""dual role""}, {""id"": 179430, ""name"": ""aftercreditsstinger""}, {""id"": 187376, ""name"": ""odd couple""}, {""id"": 188772, ""name"": ""black slave""}, {""id"": 202703, ""name"": ""deadly""}, {""id"": 206687, ""name"": ""chases and races""}, {""id"": 207928, ""name"": ""19th century""}]","[{""name"": ""Columbia Pictures"", ""id"": 5}, {""name"": ""The Weinstein Company"", ""id"": 308}]",2012-12-25,en
298,The Wolf of Wall Street,NaN,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name"": ""Drama""}, {""id"": 35, ""name"": ""Comedy""}]","[{""id"": 417, ""name"": ""corruption""}, {""id"": 572, ""name"": ""sex""}, {""id"": 738, ""name"": ""sexuality""}, {""id"": 974, ""name"": ""bank""}, {""id"": 3923, ""name"": ""humor""}, {""id"": 5565, ""name"": ""biography""}, {""id"": 5636, ""name"": ""wall street""}, {""id"": 5809, ""name"": ""marriage crisis""}, {""id"": 6974, ""name"": ""rise and fall""}, {""id"": 10631, ""name"": ""stockbroker""}, {""id"": 14964, ""name"": ""drug""}, {""id"": 179018, ""name"": ""stock broker""}]","[{""name"": ""Paramount Pictures"", ""id"": 4}, {""name"": ""Appian Way"", ""id"": 562}, {""name"": ""EMJAG Productions"", ""id"": 14654}, {""name"": ""Red Granite Pictures"", ""id"": 19177}, {""name"": ""Sikelia Productions"", ""id"": 23243}]",2013-12-25,en
329,The Lord of the Rings: The Return of the King,NaN,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""name"": ""Action""}]","[{""id"": 603, ""name"": ""elves""}, {""id"": 606, ""name"": ""orcs""}, {""id"": 609, ""name"": ""middle-earth (tolkien)""}, {""id"": 818, ""name"": ""based on novel""}, {""id"": 3301, ""name"": ""suspicion""}, {""id"": 3930, ""name"": ""bravery""}, {""id"": 6091, ""name"": ""war""}, {""id"": 9812, ""name"": ""honor""}, {""id"": 11173, ""name"": ""troll""}, {""id"": 14707, ""name"": ""brutality""}, {""id"": 14819, ""name"": ""violence""}, {""id"": 162846, ""name"": ""ghost""}, {""id"": 173700, ""name"": ""end of trilogy""}, {""id"": 207372, ""name"": ""quest""}, {""id"": 234213, ""name"": ""sword and sorcery""}]","[{""name"": ""WingNut Films"", ""id"": 11}, {""name"": ""New Line Cinema"", ""id"": 12}]",2003-12-01,en
330,The Lord of the Rings: The Two Towers,NaN,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""name"": ""Fantasy""}, {""id"": 28, ""name"": ""Action""}]","[{""id"": 603, ""name"": ""elves""}, {""id"": 606, ""name"": ""orcs""}, {""id"": 609, ""name"": ""middle-earth (tolkien)""}, {""id"": 611, ""name"": ""hobbit""}, {""id"": 818, ""name"": ""based on novel""}, {""id"": 1653, ""name"": ""explosive""}, {""id"": 1964, ""name"": ""cave""}, {""id"": 4268, ""name"": ""fort""}, {""id"": 6092, ""name"": ""army""}, {""id"": 10364, ""name"": ""mission""}, {""id"": 10563, ""name"": ""attack""}, {""id"": 33788, ""name"": ""guide""}, {""id"": 177912, ""name"": ""wizard""}, {""id"": 189093, ""name"": ""ring""}, {""id"": 234213, ""name"": ""sword and sorcery""}]","[{""name"": ""WingNut Films"", ""id"": 11}, {""name"": ""New Line Cinema"", ""id"": 12}, {""name"": ""The Saul Zaentz Company"", ""id"": 5237}]",2002-12-18,en
494,The Lion King,NaN,"[{""id"": 10751, ""name"": ""Family""}, {""id"": 16, ""name"": ""Animation""}, {""id"": 18, ""name"": ""Drama""}]","[{""id"": 2143, ""name"": ""loss of parents""}, {""id"": 5276, ""name"": ""wild boar""}, {""id"": 6464, ""name"": ""uncle""}, {""id"": 11326, ""name"": ""shaman""}, {""id"": 11436, ""name"": ""redemption""}, {""id"": 13084, ""name"": ""king""}, {""id"": 14767, ""name"": ""scar""}, {""id"": 18136, ""name"": ""hyena""}, {""id"": 18153, ""name"": ""meerkat""}]","[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""name"": ""Walt Disney Feature Animation"", ""id"": 10217}]",1994-06-23,en
634,The Matrix,NaN,"[{""id"": 28, ""name"": ""Action""}, {""id"": 878, ""name"": ""Science Fiction""}]","[{""id"": 83, ""name"": ""saving the world""}, {""id"": 310, ""name"": ""artificial intelligence""}, {""id"": 312, ""name"": ""man vs machine""}, {""id"": 490, ""name"": ""philosophy""}, {""id"": 530, ""name"": ""prophecy""}, {""id"": 779, ""name"": ""martial arts""}, {""id"": 1430, ""name"": ""self sacrifice""}, {""id"": 1721, ""name"": ""fight""}, {""id"": 3074, ""name"": ""insurgence""}, {""id"": 4563, ""name"": ""virtual reality""}, {""id"": 4565, ""name"": ""dystopia""}, {""id"": 6256, ""name"": ""truth""}, {""id"": 12190, ""name"": ""cyberpunk""}, {""id"": 187056, ""name"": ""woman director""}, {""id"": 194063, ""name"": ""messiah""}, {""id"": 221385, ""name"": ""gnosticism""}]","[{""name"": ""Village Roadshow Pictures"", ""id"": 79}, {""name"": ""Groucho II Film Partnership"", ""id"": 372}, {""name"": ""Silver Pictures"", ""id"": 1885}, {""name"": ""Warner Bros."", ""id"": 6194}]",1999-03-30,en
662,Fight Club,NaN,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 825, ""name"": ""support group""}, {""id"": 851, ""name"": ""dual identity""}, {""id"": 1541, ""name"": ""nihilism""}, {""id"": 3927, ""name"": ""rage and hate""}, {""id"": 4142, ""name"": ""insomnia""}, {""id"": 4565, ""name"": ""dystopia""}, {""id"": 14819, ""name"": ""violence""}]","[{""name"": ""Regency Enterprises"", ""id"": 508}, {""name"": ""Fox 2000 Pictures"", ""id"": 711}, {""name"": ""Taurus Film"", ""id"": 20555}, {""name"": ""Linson Films"", ""id"": 54050}, {""name"": ""Atman Entertainment"", ""id"": 54051}, {""name"": ""Knickerbocker Films"", ""id"": 54052}]",1999-10-15,en
690,The Green Mile,NaN,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 18, ""name"": ""Drama""}, {""id"": 80, ""name"": ""Crime""}]","[{""id"": 531, ""name"": ""southern usa""}, {""id"": 577, ""name"": ""black people""}, {""id"": 791, ""name"": ""mentally disabled""}, {""id"": 818, ""name"": ""based on novel""}, {""id"": 2499, ""name"": ""heal""}, {""id"": 2501, ""name"": ""death row""}, {""id"": 2881, ""name"": ""jail guard""}, {""id"": 5571, ""name"": ""great depression""}, {""id"": 9774, ""name"": ""prison guard""}, {""id"": 11263, ""name"": ""electric chair""}, {""id"": 156597, ""name"": ""magic realism""}, {""id"": 167696, ""name"": ""healing""}, {""id"": 180162, ""name"": ""death row inmate""}, {""id"": 214548, ""name"": ""1930s""}]","[{""name"": ""Castle Rock Entertainment"", ""id"": 97}, {""name"": ""Darkwoods Productions"", ""id"": 3982}, {""name"": ""Warner Bros."", ""id"": 6194}]",1999-12-10,en
809,Forrest Gump,NaN,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""name"": ""Romance""}]","[{""id"": 422, ""name"": ""vietnam veteran""}, {""id"": 458, ""name"": ""hippie""}, {""id"": 791, ""name"": ""mentally disabled""}, {""id"": 795, ""name"": ""running""}, {""id"": 818, ""name"": ""based on novel""}, {""id"": 2956, ""name"": ""vietnam""}, {""id"": 2957, ""name"": ""vietnam war""}, {""id"": 6054, ""name"": ""friendship""}, {""id"": 9673, ""name"": ""love""}, {""id"": 10235, ""name"": ""family relationships""}, {""id"": 10624, ""name"": ""bully""}, {""id"": 157499, ""name"": ""mother son relationship""}, {""id"": 162365, ""name"": ""military""}, {""id"": 162934, ""name"": ""hugging""}, {""id"": 166980, ""name"": ""shrimping""}, {""id"": 180204, ""name"": ""wounded soldier""}, {""id"": 187844, ""name"": ""flashback""}, {""id"": 208143, ""name"": ""park bench""}, {""id"": 215492, ""name"": ""amputee""}]","[{""name"": ""Paramount Pictures"", ""id"": 4}]",1994-07-06,en
1553,Se7en,NaN,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 9648, ""name"": ""Mystery""}, {""id"": 53, ""name"": ""Thriller""}]","[{""id"": 476, ""name"": ""self-fulfilling prophecy""}, {""id"": 703, ""name"": ""detective""}, {""id"": 1470, ""name"": ""s.w.a.t.""}, {""id"": 2231, ""name"": ""drug dealer""}, {""id"": 3597, ""name"": ""evisceration""}, {""id"": 3857, ""name"": ""lust and impulsiveness""}, {""id"": 3927, ""name"": ""rage and hate""}, {""id"": 3932, ""name"": ""pride and vanity""}, {""id"": 4138, ""name"": ""immoderateness""}, {""id"": 4142, ""name"": ""insomnia""}, {""id"": 5340, ""name"": ""investigation""}, {""id"": 6125, ""name"": ""pension""}, {""id"": 6149, ""name"": ""police""}, {""id"": 10714, ""name"": ""serial killer""}]","[{""name"": ""New Line Cinema"", ""id"": 12}, {""name"": ""Juno Pix"", ""id"": 4286}, {""name"": ""Cecchi Gori Pictures"", ""id"": 65394}]",1995-09-22,en
1818,Schindler's List,NaN,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 36, ""name"": ""History""}, {""id"": 10752, ""name"": ""War""}]","[{""id"": 1382, ""name"": ""factory""}, {""id"": 1631, ""name"": ""concentration camp""}, {""id"": 1701, ""name"": ""hero""}, {""id"": 1739, ""name"": ""holocaust""}, {""id"": 1956, ""name"": ""world war ii""}, {""id"": 2652, ""name"": ""nazis""}, {""id"": 3599, ""name"": ""defense industry""}, {""id"": 5565, ""name"": ""biography""}, {""id"": 194409, ""name"": ""the holocaust""}]","[{""name"": ""Universal Pictures"", ""id"": 33}, {""name"": ""Amblin Entertainment"", ""id"": 56}]",1993-11-29,en
1881,The Shawshank Redemption,NaN,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 80, ""name"": ""Crime""}]","[{""id"": 378, ""name"": ""prison""}, {""id"": 417, ""name"": ""corruption""}, {""id"": 796, ""name"": ""police brutality""}, {""id"": 2885, ""name"": ""prison cell""}, {""id"": 4779, ""name"": ""delinquent""}, {""id"": 8622, ""name"": ""parole board""}, {""id"": 9777, ""name"": ""escape from prison""}, {""id"": 12662, ""name"": ""wrongful imprisonment""}, {""id"": 180172, ""name"": ""framed for murder""}, {""id"": 207883, ""name"": ""1940s""}]","[{""name"": ""Castle Rock Entertainment"", ""id"": 97}]",1994-09-23,en
1990,The Empire Strikes Back,NaN,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""name"": ""Action""}, {""id"": 878, ""name"": ""Science Fiction""}]","[{""id"": 526, ""name"": ""rebel""}, {""id"": 803, ""name"": ""android""}, {""id"": 1423, ""name"": ""asteroid""}, {""id"": 2902, ""name"": ""space battle""}, {""id"": 3373, ""name"": ""snow storm""}, {""id"": 3388, ""name"": ""space colony""}, {""id"": 9831, ""name"": ""spaceship""}, {""id"": 10016, ""name"": ""lightsaber""}, {""id"": 10527, ""name"": ""jedi""}, {""id"": 10842, ""name"": ""good vs evil""}, {""id"": 11196, ""name"": ""rebellion""}, {""id"": 160134, ""name"": ""the force""}, {""id"": 161176, ""name"": ""space opera""}, {""id"": 178710, ""name"": ""stormtrooper""}, {""id"": 210346, ""name"": ""wookie""}, {""id"": 232452, ""name"": ""jedi master""}, {""id"": 232453, ""name"": ""jedi training""}, {""id"": 232454, ""name"": ""droid""}]","[{""name"": ""Lucasfilm"", ""id"": 1}, {""name"": ""Twentieth Century Fox Film Corporation"", ""id"": 306}]",1980-05-17,en
2091,The Silence of the Lambs,NaN,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 18, ""name"": ""Drama""}, {""id"": 53, ""name"": ""Thriller""}]","[{""id"": 818, ""name"": ""based on novel""}, {""id"": 6259, ""name"": ""psychopath""}, {""id"": 8087, ""name"": ""horror""}, {""id"": 9937, ""name"": ""suspense""}, {""id"": 10714, ""name"": ""serial killer""}, {""id"": 12565, ""name"": ""psychological thriller""}, {""id"": 14895, ""name"": ""cannibal""}, {""id"": 18525, ""name"": ""fbi agent""}, {""id"": 33872, ""name"": ""animal in cast credits""}, {""id"": 208048, ""name"": ""cannibalism""}]","[{""name"": ""Orion Pictures"", ""id"": 41}, {""name"": ""Strong Heart/Demme Production"", ""id"": 55072}]",1991-02-01,en
2285,Back to the Future,NaN,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 35, ""name"": ""Comedy""}, {""id"": 878, ""name"": ""Science Fiction""}, {""id"": 10751, ""name"": ""Family""}]","[{""id"": 389, ""name"": ""clock tower""}, {""id"": 830, ""name"": ""car race""}, {""id"": 949, ""name"": ""terrorist""}, {""id"": 951, ""name"": ""delorean""}, {""id"": 952, ""name"": ""lightning""}, {""id"": 953, ""name"": ""guitar""}, {""id"": 955, ""name"": ""plutonium""}, {""id"": 999, ""name"": ""sports car""}, {""id"": 1436, ""name"": ""inventor""}, {""id"": 1743, ""name"": ""journey in the past""}, {""id"": 4379, ""name"": ""time travel""}, {""id"": 4776, ""name"": ""race against time""}, {""id"": 9104, ""name"": ""partner""}, {""id"": 9789, ""name"": ""misfit""}, {""id"": 10125, ""name"": ""mad scientist""}, {""id"": 11860, ""name"": ""fish out of water""}, {""id"": 18425, ""name"": ""teenage love""}, {""id"": 40850, ""name"": ""destiny""}, {""id"": 186189, ""name"": ""hidden identity""}, {""id"": 187376, ""name"": ""odd couple""}, {""id"": 187710, ""name"": ""escapade""}, {""id"": 189449, ""name"": ""disorder""}, {""id"": 206687, ""name"": ""chases and races""}, {""id"": 206715, ""name"": ""love and romance""}, {""id"": 206720, ""name"": ""teenage life""}, {""id"": 206735, ""name"": ""misfit partners""}, {""id"": 206736, ""name"": ""changing the past or future""}, {""id"": 206737, ""name"": ""getting home""}, {""id"": 206738, ""name"": ""inventions and discoveries""}]","[{""name"": ""Universal Pictures"", ""id"": 33}, {""name"": ""Amblin Entertainment"", ""id"": 56}, {""name"": ""U-Drive Productions"", ""id"": 20448}]",1985-07-03,en

In [63]:
# to fill these values we download a new kaggle dataset 
outsource = pd.read_csv('imdb_top_1000.csv')
outsource.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

In [64]:
# Only using relevent columns
outsource = outsource[['Series_Title','Overview']]

In [65]:
# Renaming the outside_source to correspond to our dataset
outsource.rename(columns = {'Series_Title':'title'}, inplace = True)
outsource.rename(columns = {'Overview':'overview'}, inplace = True)

In [66]:
# Using Pandas merge feature to add the new values
movies_df = pd.merge(movies_df, outsource, on='title', how='left', suffixes=('_main', '_missing'))
movies_df['overview_main'].fillna(movies_df['overview_missing'], inplace=True)

/var/folders/1r/gc4nvyps3q953c9n35dgqswh0000gn/T/ipykernel_40232/3081809459.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  movies_df['overview_main'].fillna(movies_df['overview_missing'], inplace=True)

In [67]:
#Drop merged column
movies_df.drop(['overview_missing'], axis=1, inplace = True)
#renaming it make to 'overview'
movies_df.rename(columns = {'overview_main':'overview'}, inplace = True)

In [68]:
# Checking what titles are still left as null
movies_df[movies_df['overview'].isnull()]

,title,overview,genres,keywords,production_companies,release_date,original_language
1990,The Empire Strikes Back,NaN,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""name"": ""Action""}, {""id"": 878, ""name"": ""Science Fiction""}]","[{""id"": 526, ""name"": ""rebel""}, {""id"": 803, ""name"": ""android""}, {""id"": 1423, ""name"": ""asteroid""}, {""id"": 2902, ""name"": ""space battle""}, {""id"": 3373, ""name"": ""snow storm""}, {""id"": 3388, ""name"": ""space colony""}, {""id"": 9831, ""name"": ""spaceship""}, {""id"": 10016, ""name"": ""lightsaber""}, {""id"": 10527, ""name"": ""jedi""}, {""id"": 10842, ""name"": ""good vs evil""}, {""id"": 11196, ""name"": ""rebellion""}, {""id"": 160134, ""name"": ""the force""}, {""id"": 161176, ""name"": ""space opera""}, {""id"": 178710, ""name"": ""stormtrooper""}, {""id"": 210346, ""name"": ""wookie""}, {""id"": 232452, ""name"": ""jedi master""}, {""id"": 232453, ""name"": ""jedi training""}, {""id"": 232454, ""name"": ""droid""}]","[{""name"": ""Lucasfilm"", ""id"": 1}, {""name"": ""Twentieth Century Fox Film Corporation"", ""id"": 306}]",1980-05-17,en
2294,Spirited Away,NaN,"[{""id"": 14, ""name"": ""Fantasy""}, {""id"": 12, ""name"": ""Adventure""}, {""id"": 16, ""name"": ""Animation""}, {""id"": 10751, ""name"": ""Family""}]","[{""id"": 616, ""name"": ""witch""}, {""id"": 970, ""name"": ""parents kids relationship""}, {""id"": 2343, ""name"": ""magic""}, {""id"": 2640, ""name"": ""twilight""}, {""id"": 3762, ""name"": ""darkness""}, {""id"": 3787, ""name"": ""village and town""}, {""id"": 4652, ""name"": ""bath house""}, {""id"": 4931, ""name"": ""pig""}, {""id"": 5280, ""name"": ""ghost world""}, {""id"": 6016, ""name"": ""biology""}, {""id"": 13008, ""name"": ""train""}, {""id"": 155582, ""name"": ""amusement park""}, {""id"": 196509, ""name"": ""yokai""}, {""id"": 207695, ""name"": ""japanese mythology""}, {""id"": 210024, ""name"": ""anime""}]","[{""name"": ""Studio Ghibli"", ""id"": 10342}]",2001-07-20,ja
2656,Chiamatemi Francesco - Il Papa della gente,NaN,"[{""id"": 18, ""name"": ""Drama""}]","[{""id"": 717, ""name"": ""pope""}, {""id"": 5565, ""name"": ""biography""}]","[{""name"": ""Taodue Film"", ""id"": 45724}]",2015-12-03,it
4140,"To Be Frank, Sinatra at 100",NaN,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 6027, ""name"": ""music""}, {""id"": 225822, ""name"": ""actors""}, {""id"": 233443, ""name"": ""legendary perfomer""}, {""id"": 235277, ""name"": ""classic hollywood""}, {""id"": 235690, ""name"": ""frank sinatra""}, {""id"": 235691, ""name"": ""singers""}]","[{""name"": ""Eyeline Entertainment"", ""id"": 60343}]",2015-12-12,en
4431,Food Chains,NaN,"[{""id"": 99, ""name"": ""Documentary""}]",[],[],2014-04-26,de

In [69]:
# For these 5 overviews I decided to use brute force
# Note these overview are from
# https://www.imdb.com/title/tt0080684/
# https://www.imdb.com/title/tt0245429/
# https://www.imdb.com/title/tt3856124/plotsummary/?ref_=tt_stry_pl
# https://www.imdb.com/title/tt4704314/
# https://www.imdb.com/title/tt2141739/?ref_=ttpl_ov
movies_df['overview'][1990] = 'After the Rebels are overpowered by the Empire, Luke Skywalker begins his Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.'
movies_df['overview'][2294] = "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, a world where humans are changed into beasts."
movies_df['overview'][2656] = 'A biopic of the rise of father Jorge Mario Bergoglio SJ from a teacher in a Jesuit High School in Argentina to archbishop and cardinal of Buenos Aires to Pope of the Roman Catholic Church. The story touches on his relation with his fellow Jesuits in Argentina and Europe, to his relation with laureate writer Jorge Luis Borges, Argentine dictator Jorge Rafael Videla, and archbishops Laghi (nuncio to Argentina) and Quarracino (cardinal of Buenos Aires), up to the moment where he is elected Pope in 2013.'
movies_df['overview'][4140] = 'The life of Frank Sinatra, as an actor and singer and the steps along the way that led him to become such an icon.'
movies_df['overview'][4431] = "There is so much interest in food these days yet there is almost no interest in the hands that pick that food. In the US, farm labor has always been one of the most difficult and poorly paid jobs and has relied on some of the nation's most vulnerable people. While the legal restrictions which kept people bound to farms, like slavery, have been abolished, exploitation still exists, ranging from wage theft to modern-day slavery. These days, this exploitation is perpetuated by the corporations at the top of the food chain: supermarkets. Their buying power has kept wages pitifully low and has created a scenario where desperately poor people are willing to put up with anything to keep their jobs."

/var/folders/1r/gc4nvyps3q953c9n35dgqswh0000gn/T/ipykernel_40232/4131336829.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  movies_df['overview'][1990] = 'After the Rebels are overpowered by the Empire, Luke Skywalker begins his Jedi training with Yoda, while his friends are pursued across the galaxy by Darth Vader and bounty hunter Boba Fett.'
/var/folders/1r/gc4nvyps3q953c9n35dgqswh0000gn/T/ipykernel_40232/4131336829.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  movies_df['overview'][2294] = "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits, a world where humans are changed into beasts."
/var/folders/1r/gc4nvyps3q953c9n35dgqswh0000gn/T/ipykernel_40232/4131336829.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  movies_df['overview'][2656] = 'A biopic of the rise of father Jorge Mario Bergoglio SJ from a teacher in a Jesuit High School in Argentina to archbishop and cardinal of Buenos Aires to Pope of the Roman Catholic Church. The story touches on his relation with his fellow Jesuits in Argentina and Europe, to his relation with laureate writer Jorge Luis Borges, Argentine dictator Jorge Rafael Videla, and archbishops Laghi (nuncio to Argentina) and Quarracino (cardinal of Buenos Aires), up to the moment where he is elected Pope in 2013.'
/var/folders/1r/gc4nvyps3q953c9n35dgqswh0000gn/T/ipykernel_40232/4131336829.py:11: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  movies_df['overview'][4140] = 'The life of Frank Sinatra, as an actor and singer and the steps along the way that led him to become such an icon.'
/var/folders/1r/gc4nvyps3q953c9n35dgqswh0000gn/T/ipykernel_40232/4131336829.py:12: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  movies_df['overview'][4431] = "There is so much interest in food these days yet there is almost no interest in the hands that pick that food. In the US, farm labor has always been one of the most difficult and poorly paid jobs and has relied on some of the nation's most vulnerable people. While the legal restrictions which kept people bound to farms, like slavery, have been abolished, exploitation still exists, ranging from wage theft to modern-day slavery. These days, this exploitation is perpetuated by the corporations at the top of the food chain: supermarkets. Their buying power has kept wages pitifully low and has created a scenario where desperately poor people are willing to put up with anything to keep their jobs."

In [70]:
# Display rows where release_date is null
movies_df[movies_df['release_date'].isnull()]

,title,overview,genres,keywords,production_companies,release_date,original_language
4553,America Is Still the Place,"1971 post civil rights San Francisco seemed like the perfect place for a black Korean War veteran and his family to realize their dream of economic independence and his own chance to be his a ""boss"". Charlie Walker would soon find out how naive he was. In a city full of impostors and naysayers, he refused to take ""No"" for an answer. Until a catastrophic disaster opened a door that had never been open to a black man before. This is a story about what happened when he stepped through that door, with both feet!.",[],[],[],NaN,en

In [71]:
## Release date obtained from IMDB to replace NaN value
movies_df.loc[movies_df.title == 'America Is Still the Place','release_date'] = '2022-06-10'
movies_df.loc[movies_df.title == 'America Is Still the Place']

,title,overview,genres,keywords,production_companies,release_date,original_language
4553,America Is Still the Place,"1971 post civil rights San Francisco seemed like the perfect place for a black Korean War veteran and his family to realize their dream of economic independence and his own chance to be his a ""boss"". Charlie Walker would soon find out how naive he was. In a city full of impostors and naysayers, he refused to take ""No"" for an answer. Until a catastrophic disaster opened a door that had never been open to a black man before. This is a story about what happened when he stepped through that door, with both feet!.",[],[],[],2022-06-10,en

In [72]:
#Successful removed null values from movies data
movies_df.isnull().sum()

title                   0
overview                0
genres                  0
keywords                0
production_companies    0
release_date            0
original_language       0
dtype: int64

Note: I will get rid of the empty lists after we unpack the columns

In [73]:
#Checking for null values in credits data
credits_df.isnull().sum()

title    0
cast     0
crew     0
dtype: int64

## Data Extraction

In [74]:
# Importing Relevant Libraries
import ast
import nltk
import collections
import operator
from rake_nltk import Rake

### Extract values from a dict for a given key

In [75]:
# Creating a function to extract values from a dict - will be used for desired features 
def get_names(strlist):
    Name = []
    for i in ast.literal_eval(strlist):
        Name.append(i['name'])          # Get the value associated with the key 'name'
    return Name

In [76]:
# The 'crew' feature is formatted differently from the other desired features
# Create unique function to extract director's name from 'crew' feature
def director(strlist):
    director = []
    for i in ast.literal_eval(strlist):
        if i['job'] == 'Director':
            director.append(i['name'])          # Get directors' names
    return director

In [77]:
# create new dataframe to store features during initial cleaning
clean1_df = pd.DataFrame(movies_df['title'])
clean1_df.head()

                                      title
0                                    Avatar
1  Pirates of the Caribbean: At World's End
2                                   Spectre
3                     The Dark Knight Rises
4                               John Carter

In [78]:
# We will be putting features from 'movies' and 'credits' dataframes together. For this to be valid, we would
# initially check if our reference point, i.e. the feature 'title', is the same for both dataframes.

if movies_df['title'].equals(credits_df['title']):
    print("The 'title' columns are the same.")
else:
    print("The 'title' columns are different.")

The 'title' columns are the same.

In [79]:
# applying function to each feature that needs to be unpacked
clean1_df['genres_list'] = movies_df['genres'].apply(get_names)
clean1_df['keywords_list'] = movies_df['keywords'].apply(get_names)
clean1_df['prod_companies_list'] = movies_df['production_companies'].apply(get_names)
clean1_df['cast_list'] = credits_df['cast'].apply(get_names)
clean1_df['director_list'] = credits_df['crew'].apply(director)

In [80]:
pd.set_option('max_colwidth', None)
clean1_df.head()

,title,genres_list,keywords_list,prod_companies_list,cast_list,director_list
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colony, society, space travel, futuristic, romance, space, alien, tribe, alien planet, cgi, marine, soldier, battle, love affair, anti war, power relations, mind and soul, 3d]","[Ingenious Film Partners, Twentieth Century Fox Film Corporation, Dune Entertainment, Lightstorm Entertainment]","[Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang, Michelle Rodriguez, Giovanni Ribisi, Joel David Moore, CCH Pounder, Wes Studi, Laz Alonso, Dileep Rao, Matt Gerald, Sean Anthony Moran, Jason Whyte, Scott Lawrence, Kelly Kilgour, James Patrick Pitt, Sean Patrick Murphy, Peter Dillon, Kevin Dorman, Kelson Henderson, David Van Horn, Jacob Tomuri, Michael Blain-Rozgay, Jon Curry, Luke Hawker, Woody Schultz, Peter Mensah, Sonia Yee, Jahnel Curfman, Ilram Choi, Kyla Warren, Lisa Roumain, Debra Wilson, Chris Mala, Taylor Kibby, Jodie Landau, Julie Lamm, Cullen B. Madden, Joseph Brady Madden, Frankie Torres, Austin Wilson, Sara Wilson, Tamica Washington-Miller, Lucy Briant, Nathan Meister, Gerry Blair, Matthew Chamberlain, Paul Yates, Wray Wilson, James Gaylyn, Melvin Leno Clark III, Carvon Futrell, Brandon Jelkes, Micah Moch, Hanniyah Muhammad, Christopher Nolen, Christa Oliver, April Marie Thomas, Bravita A. Threatt, Colin Bleasdale, Mike Bodnar, Matt Clayton, Nicole Dionne, Jamie Harrison, Allan Henry, Anthony Ingruber, Ashley Jeffery, Dean Knowsley, Joseph Mika-Hunt, Terry Notary, Kai Pantano, Logan Pithyou, Stuart Pollock, Raja, Gareth Ruck, Rhian Sheehan, T. J. Storm, Jodie Taylor, Alicia Vela-Bailey, Richard Whiteside, Nikie Zambo, Julene Renee]",[James Cameron]
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india trading company, love of one's life, traitor, shipwreck, strong woman, ship, alliance, calypso, afterlife, fighter, pirate, swashbuckler, aftercreditsstinger]","[Walt Disney Pictures, Jerry Bruckheimer Films, Second Mate Productions]","[Johnny Depp, Orlando Bloom, Keira Knightley, Stellan Skarsgård, Chow Yun-fat, Bill Nighy, Geoffrey Rush, Jack Davenport, Kevin McNally, Tom Hollander, Naomie Harris, Jonathan Pryce, Keith Richards, Lee Arenberg, Mackenzie Crook, Greg Ellis, David Bailie, Martin Klebba, David Schofield, Lauren Maher, Vanessa Branch, Angus Barnett, Giles New, Reggie Lee, Dominic Scott Kay, Takayo Fischer, David Meunier, Ho-Kwan Tse, Andy Beckwith, Peter Donald Badalamenti II, Christopher S. Capp, Keith Richards, Hakeem Kae-Kazim, Ghassan Massoud]",[Gore Verbinski]
2,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi6, british secret service, united kingdom]","[Columbia Pictures, Danjaq, B24]","[Daniel Craig, Christoph Waltz, Léa Seydoux, Ralph Fiennes, Monica Bellucci, Ben Whishaw, Naomie Harris, Dave Bautista, Andrew Scott, Rory Kinnear, Jesper Christensen, Alessandro Cremona, Stephanie Sigman, Tenoch Huerta, Adriana Paz, Domenico Fortunato, Marco Zingaro, Stefano Elfi DiClaudia, Ian Bonar, Tam Williams, Richard Banham, Pip Carter, Simon Lenagan, Alessandro Bressanello, Marc Zinga, Brigitte Millar, Adel Bencherif, Gediminas Adomaitis, Peppe Lanzetta, Francesco Arca, Matteo Taranto, Emilio Aniba, Benito Sagredo, Dai Tabuchi, George Lasha, Sargon Yelda, Andy Cheung, Erick Hayden, Oleg Mirochnikov, Antonio Salines, Miloud Mourad Benamara, Gido Schimanski, Nigel Barber, Patrice Naiambana, Stephane Cornicard, Gary Fannin, Sadao Ueda, Phillip Law, Wai Wong, Joseph Balderrama, Eiji Mihara, Junichi Kajioka, Victor Schefé, Harald Windisch, Tristan Matthiae, Detlef Bothe, Bodo Friesecke, Wilhem Iben, Noemi Krausz, Noah Saavedra, Francis Attakpah, Michael Glantschnig, Marlon Boess, Marie Wohlmuth, Lili Epply, Konstantin Gerlach, Lara Parmiani, Umit Ulgen, Amra Mallassi, Ziad Abaza, Walid Mumuni, Derek Horsham, Nari Blair-Mangat, Michael White, Adam McGrady, Nader Dernaika, Pezhmaan Alinia, Judi Dench, Neve Gachev, Karl Farrer, Kim Adis, Maurisa Selene Coleman, Matija Mondi Matović]",[Sam Mendes]
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret identity, burglar, hostage drama, time bomb, gotham city, vigilante, cover-up, superhero, villainess, tragic hero, terrorism, destruction, catwoman, cat burglar, imax, flood, criminal underworld, batman]","[Legendary Pictures, Warner Bros., DC Entertainment, Syncopy]","[Christian Bale, Michael Caine, Gary Oldman, Anne Hathaway, Tom Hardy, Marion Cotillard, Joseph Gordon-Levitt, Morgan Freeman, Cillian Murphy, Juno Temple, Liam Neeson, Matthew Modine, Alon Aboutboul, Ben Mendelsohn, Nestor Carbonell, Josh Pence, Tom Conti, Joey King, Warren Brown, Daniel Sunjata, Sam Kennard, Aliash Tepina, Nick Julian, Miranda Nolan, Claire Julien, Aidan Gillen, Burn Gorman, Brett Cullen, Reggie Lee, Joseph Lyle Taylor, Chris Ellis, Duane Henry, James Harvey Ward, Gonzalo Menendez, Cameron Jack, Lex Daniel, Tyler Dean Flores, Thomas Lennon, Trevor White, Rob Brown, Fredric Lehne, Courtney Munch, Chris Hill, Travis Guba, Jay Benedict, Will Estes, David Dayan Fisher, Glen Powell, Russ Fega, Andres Perez-Molina, Brent Briscoe, John Nolan, Oliver Cotton, Mark Killeen, Sarah Goldberg, John MacMillan, Robert Wisdom, Ronnie Gene Blevins, John Hollingworth, Ian Bohen, Uri Gavriel, Noel Gugliemi, Hector Atreyu Ruiz, Patrick Cox, Aramis Knight, Josh Stewart, William Devane, David Gyasi, Patrick Jordan, Joshua Elijah Reese, Desmond Harrington, Mychael Bates, Tomas Arana, Peter Holden, David Monahan, Jillian Armenante, Aja Evans, Aldous Davidson, Wade Williams, Jake Canuso, Massi Furlan, Christopher Judge, Patrick Leahy, Todd Gearhart, Marc Abbink, Isiah Adams, Charlie Alejandro, Robert Arensen, Grant Babbitt, Fileena Bahris, Rick Bolander, Kyle Patrick Brennan, Scott Churchson, Bill Cowher, Graham Curry, Stephanie Domini Ehlert, John Farrer, Frank Fata, Christopher Bryan Gomez, Vito Grassi, ...]",[Christopher Nolan]
4,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel, princess, alien, steampunk, martian, escape, edgar rice burroughs, alien race, superhuman strength, mars civilization, sword and planet, 19th century, 3d]",[Walt Disney Pictures],"[Taylor Kitsch, Lynn Collins, Samantha Morton, Willem Dafoe, Thomas Haden Church, Mark Strong, Ciarán Hinds, Dominic West, James Purefoy, Bryan Cranston, Polly Walker, Daryl Sabara, Arkie Reece, Davood Ghadami, Pippa Nixon, James Embree, Philip Philmar, Emily Tierney, Edmund Kente, Nicholas Woodeson, Kyle Agnew, Don Stark, Josh Daugherty, Jared Cyr, Christopher Goodman, Amanda Clayton, Joseph Billingiere]",[Andrew Stanton]

In [81]:
clean1_df['genres_list'].value_counts()

genres_list
[Drama]                                         370
[Comedy]                                        282
[Drama, Romance]                                164
[Comedy, Romance]                               144
[Comedy, Drama]                                 142
                                               ...
[Adventure, Action, Comedy, Romance]              1
[Action, Fantasy, Science Fiction, Thriller]      1
[Science Fiction, Comedy, Adventure]              1
[Drama, Thriller, Horror]                         1
[Comedy, Drama, Romance, TV Movie]                1
Name: count, Length: 1175, dtype: int64

In [82]:
# Finding Empty Values in the previously packed columns
def count_empty_lists(val):
    if isinstance(val, list):
        return 1 if not val else 0
    else:
        return 0

empty_counts = clean1_df.applymap(count_empty_lists)

# sum the empty_counts column-wise to get the total empty lists in each column
total_empty_lists = empty_counts.sum(axis=0)

# print the result
print(total_empty_lists)

title                    0
genres_list             28
keywords_list          412
prod_companies_list    351
cast_list               43
director_list           30
dtype: int64

/var/folders/1r/gc4nvyps3q953c9n35dgqswh0000gn/T/ipykernel_40232/3985591865.py:8: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  empty_counts = clean1_df.applymap(count_empty_lists)

In [83]:
# Replacing empty values with values that wont interfere with the similarity matrix
def replace_empty_values(row):
    for col in clean1_df.columns:
        if len(row[col]) == 0:
            for other_col in clean1_df.columns:
                if col != other_col and len(row[other_col]) > 0:
                    row[col] = row[other_col]
                    break
    return row

clean1_df = clean1_df.apply(replace_empty_values, axis=1)

empty_counts = clean1_df.applymap(count_empty_lists)
total_empty_lists = empty_counts.sum(axis=0)
print(total_empty_lists)

title                  0
genres_list            0
keywords_list          0
prod_companies_list    0
cast_list              0
director_list          0
dtype: int64

/var/folders/1r/gc4nvyps3q953c9n35dgqswh0000gn/T/ipykernel_40232/2446526433.py:13: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  empty_counts = clean1_df.applymap(count_empty_lists)

### Extracting Important Words

In [ ]:
# function to extract the N most important keywords
# N is set by parameter top_n_keywords (default = 5, but we'll take top 30)
# lowercase, nremove stopwords
import nltk

resources = {
    "corpora/stopwords": "stopwords",
    "tokenizers/punkt": "punkt",
    "tokenizers/punkt_tab": "punkt_tab",  # needed on newer NLTK builds
    "corpora/wordnet": "wordnet",
    "corpora/omw-1.4": "omw-1.4",
}

for path, pkg in resources.items():
    try:
        nltk.data.find(path)
    except LookupError:
        nltk.download(pkg)

def extract_key_words(input_str, top_n_keywords=30):
    r = Rake()
    r.extract_keywords_from_text(input_str.lower())
    key_words_dict_scores = r.get_word_degrees()
    sorted_key_words_dict_scores = sorted(key_words_dict_scores.items(), key=operator.itemgetter(1), reverse=True)
    sorted_dict = collections.OrderedDict(sorted_key_words_dict_scores)
    
    # Change top_n_keywords as appropriate
    return sorted_dict, list(sorted_dict.keys())[:top_n_keywords]

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/subhantariq/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [85]:

clean1_df['overview_key_list'] = movies_df['overview'].apply(lambda x: extract_key_words(x)[1])

LookupError:
**********************************************************************
  Resource 'punkt_tab' not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt_tab')

  For more information see: https://www.nltk.org/data.html

  Attempted to load 'tokenizers/punkt_tab/english/'

  Searched in:
    - '/Users/subhantariq/nltk_data'
    - '/Users/subhantariq/Desktop/Personal_Projects/python-project/Movie-Recommendation-Project/.venv/nltk_data'
    - '/Users/subhantariq/Desktop/Personal_Projects/python-project/Movie-Recommendation-Project/.venv/share/nltk_data'
    - '/Users/subhantariq/Desktop/Personal_Projects/python-project/Movie-Recommendation-Project/.venv/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
**********************************************************************

In [ ]:
clean1_df

,title,genres_list,keywords_list,prod_companies_list,cast_list,director_list,overview_key_list
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colony, society, space travel, futuristic, romance, space, alien, tribe, alien planet, cgi, marine, soldier, battle, love affair, anti war, power relations, mind and soul, 3d]","[Ingenious Film Partners, Twentieth Century Fox Film Corporation, Dune Entertainment, Lightstorm Entertainment]","[Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang, Michelle Rodriguez, Giovanni Ribisi, Joel David Moore, CCH Pounder, Wes Studi, Laz Alonso, Dileep Rao, Matt Gerald, Sean Anthony Moran, Jason Whyte, Scott Lawrence, Kelly Kilgour, James Patrick Pitt, Sean Patrick Murphy, Peter Dillon, Kevin Dorman, Kelson Henderson, David Van Horn, Jacob Tomuri, Michael Blain-Rozgay, Jon Curry, Luke Hawker, Woody Schultz, Peter Mensah, Sonia Yee, Jahnel Curfman, Ilram Choi, Kyla Warren, Lisa Roumain, Debra Wilson, Chris Mala, Taylor Kibby, Jodie Landau, Julie Lamm, Cullen B. Madden, Joseph Brady Madden, Frankie Torres, Austin Wilson, Sara Wilson, Tamica Washington-Miller, Lucy Briant, Nathan Meister, Gerry Blair, Matthew Chamberlain, Paul Yates, Wray Wilson, James Gaylyn, Melvin Leno Clark III, Carvon Futrell, Brandon Jelkes, Micah Moch, Hanniyah Muhammad, Christopher Nolen, Christa Oliver, April Marie Thomas, Bravita A. Threatt, Colin Bleasdale, Mike Bodnar, Matt Clayton, Nicole Dionne, Jamie Harrison, Allan Henry, Anthony Ingruber, Ashley Jeffery, Dean Knowsley, Joseph Mika-Hunt, Terry Notary, Kai Pantano, Logan Pithyou, Stuart Pollock, Raja, Gareth Ruck, Rhian Sheehan, T. J. Storm, Jodie Taylor, Alicia Vela-Bailey, Richard Whiteside, Nikie Zambo, Julene Renee]",[James Cameron],"[22nd, century, paraplegic, marine, moon, pandora, unique, mission, becomes, torn, following, orders, alien, civilization, dispatched, protecting]"
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india trading company, love of one's life, traitor, shipwreck, strong woman, ship, alliance, calypso, afterlife, fighter, pirate, swashbuckler, aftercreditsstinger]","[Walt Disney Pictures, Jerry Bruckheimer Films, Second Mate Productions]","[Johnny Depp, Orlando Bloom, Keira Knightley, Stellan Skarsgård, Chow Yun-fat, Bill Nighy, Geoffrey Rush, Jack Davenport, Kevin McNally, Tom Hollander, Naomie Harris, Jonathan Pryce, Keith Richards, Lee Arenberg, Mackenzie Crook, Greg Ellis, David Bailie, Martin Klebba, David Schofield, Lauren Maher, Vanessa Branch, Angus Barnett, Giles New, Reggie Lee, Dominic Scott Kay, Takayo Fischer, David Meunier, Ho-Kwan Tse, Andy Beckwith, Peter Donald Badalamenti II, Christopher S. Capp, Keith Richards, Hakeem Kae-Kazim, Ghassan Massoud]",[Gore Verbinski],"[captain, barbossa, long, believed, come, back, elizabeth, swann, dead, life, headed, edge, earth, turner, nothing, quite, seems]"
2,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi6, british secret service, united kingdom]","[Columbia Pictures, Danjaq, B24]","[Daniel Craig, Christoph Waltz, Léa Seydoux, Ralph Fiennes, Monica Bellucci, Ben Whishaw, Naomie Harris, Dave Bautista, Andrew Scott, Rory Kinnear, Jesper Christensen, Alessandro Cremona, Stephanie Sigman, Tenoch Huerta, Adriana Paz, Domenico Fortunato, Marco Zingaro, Stefano Elfi DiClaudia, Ian Bonar, Tam Williams, Richard Banham, Pip Carter, Simon Lenagan, Alessandro Bressanello, Marc Zinga, Brigitte Millar, Adel Bencherif, Gediminas Adomaitis, Peppe Lanzetta, Francesco Arca, Matteo Taranto, Emilio Aniba, Benito Sagredo, Dai Tabuchi, George Lasha, Sargon Yelda, Andy Cheung, Erick Hayden, Oleg Mirochnikov, Antonio Salines, Miloud Mourad Benamara, Gido Schimanski, Nigel Barber, Patrice Naiambana, Stephane Cornicard, Gary Fannin, Sadao Ueda, Phillip Law, Wai Wong, Joseph Balderrama, Eiji Mihara, Junichi Kajioka, Victor Schefé, Harald Windisch, Tristan Matthiae, Detlef Bothe, Bodo Friesecke, Wilhem Iben, Noemi Krausz, Noah Saavedra, Francis Attakpah, Michael Glantschnig, Marlon Boess, Marie Wohlmuth, Lili Epply, Konstantin Gerlach, Lara Parmiani, Umit Ulgen, Amra Mallassi, Ziad Abaza, Walid Mumuni, Derek Horsham, Nari Blair-Mangat, Michael White, Adam McGrady, Nader Dernaika, Pezhmaan Alinia, Judi Dench, Neve Gachev, Karl Farrer, Kim Adis, Maurisa Selene Coleman, Matija Mondi Matović]",[Sam Mendes],"[bond, terrible, truth, behind, spectre, battles, political, forces, secret, service, alive, peels, back, cryptic, message, ’, past, sends, sinister, organization, trail, uncover, keep, layers, deceit, reveal]"
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret identity, burglar, hostage drama, time bomb, gotham city, vigilante, cover-up, superhero, villainess, tragic hero, terrorism, destruction, catwoman, cat burglar, imax, flood, criminal underworld, batman]","[Legendary Pictures, Warner Bros., DC Entertainment, Syncopy]","[Christian Bale, Michael Caine, Gary Oldman, Anne Hathaway, Tom Hardy, Marion Cotillard, Joseph Gordon-Levitt, Morgan Freeman, Cillian Murphy, Juno Temple, Liam Neeson, Matthew Modine, Alon Aboutboul, Ben Mendelsohn, Nestor Carbonell, Josh Pence, Tom Conti, Joey King, Warren Brown, Daniel Sunjata, Sam Kennard, Aliash Tepina, Nick Julian, Miranda Nolan, Claire Julien, Aidan Gillen, Burn Gorman, Brett Cullen, Reggie Lee, Joseph Lyle Taylor, Chris Ellis, Duane Henry, James Harvey Ward, Gonzalo Menendez, Cameron Jack, Lex Daniel, Tyler Dean Flores, Thomas Lennon, Trevor White, Rob Brown, Fredric Lehne, Courtney Munch, Chris Hill, Travis Guba, Jay Benedict, Will Estes, David Dayan Fisher, Glen Powell, Russ Fega, Andres Perez-Molina, Brent Briscoe, John Nolan, Oliver Cotton, Mark Killeen, Sarah Goldberg, John MacMillan, Robert Wisdom, Ronnie Gene Blevins, John Hollingworth, Ian Bohen, Uri Gavriel, Noel Gugliemi, Hector Atreyu Ruiz, Patrick Cox, Aramis Knight, Josh Stewart, William Devane, David Gyasi, Patrick Jordan, Joshua Elijah Reese, Desmond Harrington, Mychael Bates, Tomas Arana, Peter Holden, David Monahan, Jillian Armenante, Aja Evans, Aldous Davidson, Wade Williams, Jake Canuso, Massi Furlan, Christopher Judge, Patrick Leahy, Todd Gearhart, Marc Abbink, Isiah Adams, Charlie Alejandro, Robert Arensen, Grant Babbitt, Fileena Bahris, Rick Bolander, Kyle Patrick Brennan, Scott Churchson, Bill Cowher, Graham Curry, Stephanie Domini Ehlert, John Farrer, Frank Fata, Christopher Bryan Gomez, Vito Grassi, ...]",[Christopher Nolan],"[attorney, gotham, dent, batman, city, district, harvey, police, department, assumes, responsibility, eight, years, later, mysterious, selina, kyle, new, terrorist, leader, dark, knight, resurfaces, protect, late, subsequently, hunted, encounters, villainous, bane]"
4,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel, princess, alien, steampunk, martian, escape, edgar rice burroughs, alien race, superhuman strength, mars civilization, sword and planet, 19th century, 3d]",[Walt Disney Pictures],"[Taylor Kitsch, Lynn Collins, Samantha Morton, Willem Dafoe, Thomas Haden Church, Mark Strong, Ciarán Hinds, Dominic West, James Purefoy, Bryan Cranston, Polly Walker, Daryl Sabara, Arkie Reece, Davood Ghadami, Pippa Nixon, James Embree, Philip Philmar, Emily Tierney, Edmund Kente, Nicholas Woodeson, Kyle Agnew, Don Stark, Josh Daugherty, Jared Cyr, Christopher Goodman, Amanda Clayton, Joseph Billingiere]",[Andrew Stanton],"[carter, former, military, captain, reluctantly, becomes, embroiled, john, inexplicably, transported, exotic, planet, barsoom, epic, conflict, rediscovers, people, rests, war, weary, mysterious, mars, world, brink, collapse, humanity, realizes, survival, hands]"
...,...,...,...,...,...,...,...
4798,El Mariachi,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, paper knife, guitar case]",[Columbia Pictures],"[Carlos Gallardo, Jaime de Hoyos, Peter Marquardt, Reinol Martinez, Ramiro Gomez, Consuelo Gómez, Juan García]",[Robert Rodriguez],"[el, mariachi, guitar, town, case, henchmen, mistake, another, visitor, ..., around, trying, family, tradition, find, work, killer, drug, lord, wants, play, carry, unfortunately, tries, carries, guns, azul, chase, kill, get]"
4799,Newlyweds,"[Comedy, Romance]",Newlyweds,Newlyweds,"[Edward Burns, Kerry Bishé, Marsha Dietlein, Caitlin Fitzgerald, Daniella Pineda]",[Edward Burns],"[newlywed, couple, respective, sisters, honeymoon, upended, arrivals]"
4800,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investigation, team, postal worker]","[Front Street Pictures, Muse Entertainment Enterprises]","[Eric Mabius, Kristin Booth, Crystal Lowe, Geoff Gustafson, Benjamin Hollingsworth, Laci J Mailey, Daphne Zuniga]",[Scott Smith],"[office, dead, letter, seemingly, undeliverable, takes, past, save, lives, reunite, old, loves, dedicated, quartet, civil, servants, postal, system, elite, team, mail, detectives, post, unpredictable, world, solve, crimes, change, futures, arriving]"
4801,Shanghai Calling,Shanghai Calling,Shanghai Calling,Shanghai Calling,"[Daniel Henney, Eliza Coupe, Bill Paxton, Alan Ruck, Zhu Shimao]",[Daniel Hsia],"[sam, ambitious, new, york, attorney, legal, beautiful, relocation, specialist, smart, assistant, shanghai, immediately, stumbles, mess, could, end, connected, old, clever, journalist, might, find, romance, com, )., sent, assignment, career, help]"
4802,My Date with Drew,[Documentary],"[obsession, camcorder, crush, dream girl]","[rusty bear entertainment, lucky crow films]","[Drew Barrymore, Brian Herzlinger, Corey Feldman, Eric Roberts, Griffin Dunne, Samuel L. Jackson, Matt LeBlanc, Bill D'Elia]","[Brian Herzlinger, Jon Gunn, Brett Winn]","[brian, herzlinger, drew, barrymore, 20, years, later, one, small, problem, old, aspiring, filmmaker, ever, since, second, grade, first, saw, lifelong, dream, broke, 27, new, jersey, e, extraterrestrial, crush, decided, try]"

In [ ]:
# Create function to remove punctuation
import string

def no_punc(mylist):
    newlist = []
    for element in mylist:
        translator = str.maketrans('','',string.punctuation)
        newelement = element.translate(translator)
        newlist.append(newelement)
    return newlist

In [ ]:
# Apply function to remove punctuation, for every value in every column except the 'title' column

clean1_df.iloc[:,1:] = clean1_df.iloc[:,1:].applymap(no_punc)
clean1_df

,title,genres_list,keywords_list,prod_companies_list,cast_list,director_list,overview_key_list
0,Avatar,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colony, society, space travel, futuristic, romance, space, alien, tribe, alien planet, cgi, marine, soldier, battle, love affair, anti war, power relations, mind and soul, 3d]","[Ingenious Film Partners, Twentieth Century Fox Film Corporation, Dune Entertainment, Lightstorm Entertainment]","[Sam Worthington, Zoe Saldana, Sigourney Weaver, Stephen Lang, Michelle Rodriguez, Giovanni Ribisi, Joel David Moore, CCH Pounder, Wes Studi, Laz Alonso, Dileep Rao, Matt Gerald, Sean Anthony Moran, Jason Whyte, Scott Lawrence, Kelly Kilgour, James Patrick Pitt, Sean Patrick Murphy, Peter Dillon, Kevin Dorman, Kelson Henderson, David Van Horn, Jacob Tomuri, Michael BlainRozgay, Jon Curry, Luke Hawker, Woody Schultz, Peter Mensah, Sonia Yee, Jahnel Curfman, Ilram Choi, Kyla Warren, Lisa Roumain, Debra Wilson, Chris Mala, Taylor Kibby, Jodie Landau, Julie Lamm, Cullen B Madden, Joseph Brady Madden, Frankie Torres, Austin Wilson, Sara Wilson, Tamica WashingtonMiller, Lucy Briant, Nathan Meister, Gerry Blair, Matthew Chamberlain, Paul Yates, Wray Wilson, James Gaylyn, Melvin Leno Clark III, Carvon Futrell, Brandon Jelkes, Micah Moch, Hanniyah Muhammad, Christopher Nolen, Christa Oliver, April Marie Thomas, Bravita A Threatt, Colin Bleasdale, Mike Bodnar, Matt Clayton, Nicole Dionne, Jamie Harrison, Allan Henry, Anthony Ingruber, Ashley Jeffery, Dean Knowsley, Joseph MikaHunt, Terry Notary, Kai Pantano, Logan Pithyou, Stuart Pollock, Raja, Gareth Ruck, Rhian Sheehan, T J Storm, Jodie Taylor, Alicia VelaBailey, Richard Whiteside, Nikie Zambo, Julene Renee]",[James Cameron],"[22nd, century, paraplegic, marine, moon, pandora, unique, mission, becomes, torn, following, orders, alien, civilization, dispatched, protecting]"
1,Pirates of the Caribbean: At World's End,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india trading company, love of ones life, traitor, shipwreck, strong woman, ship, alliance, calypso, afterlife, fighter, pirate, swashbuckler, aftercreditsstinger]","[Walt Disney Pictures, Jerry Bruckheimer Films, Second Mate Productions]","[Johnny Depp, Orlando Bloom, Keira Knightley, Stellan Skarsgård, Chow Yunfat, Bill Nighy, Geoffrey Rush, Jack Davenport, Kevin McNally, Tom Hollander, Naomie Harris, Jonathan Pryce, Keith Richards, Lee Arenberg, Mackenzie Crook, Greg Ellis, David Bailie, Martin Klebba, David Schofield, Lauren Maher, Vanessa Branch, Angus Barnett, Giles New, Reggie Lee, Dominic Scott Kay, Takayo Fischer, David Meunier, HoKwan Tse, Andy Beckwith, Peter Donald Badalamenti II, Christopher S Capp, Keith Richards, Hakeem KaeKazim, Ghassan Massoud]",[Gore Verbinski],"[captain, barbossa, long, believed, come, back, elizabeth, swann, dead, life, headed, edge, earth, turner, nothing, quite, seems]"
2,Spectre,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi6, british secret service, united kingdom]","[Columbia Pictures, Danjaq, B24]","[Daniel Craig, Christoph Waltz, Léa Seydoux, Ralph Fiennes, Monica Bellucci, Ben Whishaw, Naomie Harris, Dave Bautista, Andrew Scott, Rory Kinnear, Jesper Christensen, Alessandro Cremona, Stephanie Sigman, Tenoch Huerta, Adriana Paz, Domenico Fortunato, Marco Zingaro, Stefano Elfi DiClaudia, Ian Bonar, Tam Williams, Richard Banham, Pip Carter, Simon Lenagan, Alessandro Bressanello, Marc Zinga, Brigitte Millar, Adel Bencherif, Gediminas Adomaitis, Peppe Lanzetta, Francesco Arca, Matteo Taranto, Emilio Aniba, Benito Sagredo, Dai Tabuchi, George Lasha, Sargon Yelda, Andy Cheung, Erick Hayden, Oleg Mirochnikov, Antonio Salines, Miloud Mourad Benamara, Gido Schimanski, Nigel Barber, Patrice Naiambana, Stephane Cornicard, Gary Fannin, Sadao Ueda, Phillip Law, Wai Wong, Joseph Balderrama, Eiji Mihara, Junichi Kajioka, Victor Schefé, Harald Windisch, Tristan Matthiae, Detlef Bothe, Bodo Friesecke, Wilhem Iben, Noemi Krausz, Noah Saavedra, Francis Attakpah, Michael Glantschnig, Marlon Boess, Marie Wohlmuth, Lili Epply, Konstantin Gerlach, Lara Parmiani, Umit Ulgen, Amra Mallassi, Ziad Abaza, Walid Mumuni, Derek Horsham, Nari BlairMangat, Michael White, Adam McGrady, Nader Dernaika, Pezhmaan Alinia, Judi Dench, Neve Gachev, Karl Farrer, Kim Adis, Maurisa Selene Coleman, Matija Mondi Matović]",[Sam Mendes],"[bond, terrible, truth, behind, spectre, battles, political, forces, secret, service, alive, peels, back, cryptic, message, ’, past, sends, sinister, organization, trail, uncover, keep, layers, deceit, reveal]"
3,The Dark Knight Rises,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret identity, burglar, hostage drama, time bomb, gotham city, vigilante, coverup, superhero, villainess, tragic hero, terrorism, destruction, catwoman, cat burglar, imax, flood, criminal underworld, batman]","[Legendary Pictures, Warner Bros, DC Entertainment, Syncopy]","[Christian Bale, Michael Caine, Gary Oldman, Anne Hathaway, Tom Hardy, Marion Cotillard, Joseph GordonLevitt, Morgan Freeman, Cillian Murphy, Juno Temple, Liam Neeson, Matthew Modine, Alon Aboutboul, Ben Mendelsohn, Nestor Carbonell, Josh Pence, Tom Conti, Joey King, Warren Brown, Daniel Sunjata, Sam Kennard, Aliash Tepina, Nick Julian, Miranda Nolan, Claire Julien, Aidan Gillen, Burn Gorman, Brett Cullen, Reggie Lee, Joseph Lyle Taylor, Chris Ellis, Duane Henry, James Harvey Ward, Gonzalo Menendez, Cameron Jack, Lex Daniel, Tyler Dean Flores, Thomas Lennon, Trevor White, Rob Brown, Fredric Lehne, Courtney Munch, Chris Hill, Travis Guba, Jay Benedict, Will Estes, David Dayan Fisher, Glen Powell, Russ Fega, Andres PerezMolina, Brent Briscoe, John Nolan, Oliver Cotton, Mark Killeen, Sarah Goldberg, John MacMillan, Robert Wisdom, Ronnie Gene Blevins, John Hollingworth, Ian Bohen, Uri Gavriel, Noel Gugliemi, Hector Atreyu Ruiz, Patrick Cox, Aramis Knight, Josh Stewart, William Devane, David Gyasi, Patrick Jordan, Joshua Elijah Reese, Desmond Harrington, Mychael Bates, Tomas Arana, Peter Holden, David Monahan, Jillian Armenante, Aja Evans, Aldous Davidson, Wade Williams, Jake Canuso, Massi Furlan, Christopher Judge, Patrick Leahy, Todd Gearhart, Marc Abbink, Isiah Adams, Charlie Alejandro, Robert Arensen, Grant Babbitt, Fileena Bahris, Rick Bolander, Kyle Patrick Brennan, Scott Churchson, Bill Cowher, Graham Curry, Stephanie Domini Ehlert, John Farrer, Frank Fata, Christopher Bryan Gomez, Vito Grassi, ...]",[Christopher Nolan],"[attorney, gotham, dent, batman, city, district, harvey, police, department, assumes, responsibility, eight, years, later, mysterious, selina, kyle, new, terrorist, leader, dark, knight, resurfaces, protect, late, subsequently, hunted, encounters, villainous, bane]"
4,John Carter,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel, princess, alien, steampunk, martian, escape, edgar rice burroughs, alien race, superhuman strength, mars civilization, sword and planet, 19th century, 3d]",[Walt Disney Pictures],"[Taylor Kitsch, Lynn Collins, Samantha Morton, Willem Dafoe, Thomas Haden Church, Mark Strong, Ciarán Hinds, Dominic West, James Purefoy, Bryan Cranston, Polly Walker, Daryl Sabara, Arkie Reece, Davood Ghadami, Pippa Nixon, James Embree, Philip Philmar, Emily Tierney, Edmund Kente, Nicholas Woodeson, Kyle Agnew, Don Stark, Josh Daugherty, Jared Cyr, Christopher Goodman, Amanda Clayton, Joseph Billingiere]",[Andrew Stanton],"[carter, former, military, captain, reluctantly, becomes, embroiled, john, inexplicably, transported, exotic, planet, barsoom, epic, conflict, rediscovers, people, rests, war, weary, mysterious, mars, world, brink, collapse, humanity, realizes, survival, hands]"
...,...,...,...,...,...,...,...
4798,El Mariachi,"[Action, Crime, Thriller]","[united states–mexico barrier, legs, arms, paper knife, guitar case]",[Columbia Pictures],"[Carlos Gallardo, Jaime de Hoyos, Peter Marquardt, Reinol Martinez, Ramiro Gomez, Consuelo Gómez, Juan García]",[Robert Rodriguez],"[el, mariachi, guitar, town, case, henchmen, mistake, another, visitor, , around, trying, family, tradition, find, work, killer, drug, lord, wants, play, carry, unfortunately, tries, carries, guns, azul, chase, kill, get]"
4799,Newlyweds,"[Comedy, Romance]","[N, e, w, l, y, w, e, d, s]","[N, e, w, l, y, w, e, d, s]","[Edward Burns, Kerry Bishé, Marsha Dietlein, Caitlin Fitzgerald, Daniella Pineda]",[Edward Burns],"[newlywed, couple, respective, sisters, honeymoon, upended, arrivals]"
4800,"Signed, Sealed, Delivered","[Comedy, Drama, Romance, TV Movie]","[date, love at first sight, narration, investigation, team, postal worker]","[Front Street Pictures, Muse Entertainment Enterprises]","[Eric Mabius, Kristin Booth, Crystal Lowe, Geoff Gustafson, Benjamin Hollingsworth, Laci J Mailey, Daphne Zuniga]",[Scott Smith],"[office, dead, letter, seemingly, undeliverable, takes, past, save, lives, reunite, old, loves, dedicated, quartet, civil, servants, postal, system, elite, team, mail, detectives, post, unpredictable, world, solve, crimes, change, futures, arriving]"
4801,Shanghai Calling,"[S, h, a, n, g, h, a, i, , C, a, l, l, i, n, g]","[S, h, a, n, g, h, a, i, , C, a, l, l, i, n, g]","[S, h, a, n, g, h, a, i, , C, a, l, l, i, n, g]","[Daniel Henney, Eliza Coupe, Bill Paxton, Alan Ruck, Zhu Shimao]",[Daniel Hsia],"[sam, ambitious, new, york, attorney, legal, beautiful, relocation, specialist, smart, assistant, shanghai, immediately, stumbles, mess, could, end, connected, old, clever, journalist, might, find, romance, com, , sent, assignment, career, help]"
4802,My Date with Drew,[Documentary],"[obsession, camcorder, crush, dream girl]","[rusty bear entertainment, lucky crow films]","[Drew Barrymore, Brian Herzlinger, Corey Feldman, Eric Roberts, Griffin Dunne, Samuel L Jackson, Matt LeBlanc, Bill DElia]","[Brian Herzlinger, Jon Gunn, Brett Winn]","[brian, herzlinger, drew, barrymore, 20, years, later, one, small, problem, old, aspiring, filmmaker, ever, since, second, grade, first, saw, lifelong, dream, broke, 27, new, jersey, e, extraterrestrial, crush, decided, try]"

In [ ]:
# Creating function to lowercase all the letters in the list

def lowercase(mylist):
    newlist = []
    for element in mylist:
        newelement = element.lower()
        newlist.append(newelement)
    return newlist

In [ ]:
# Apply function to lower case all elements, for every value in every column except the 'title' column
# since will be redundant for 'overview' feature

clean1_df.iloc[:,1:] = clean1_df.iloc[:,1:].applymap(lowercase)
clean1_df.head()

,title,genres_list,keywords_list,prod_companies_list,cast_list,director_list,overview_key_list
0,Avatar,"[action, adventure, fantasy, science fiction]","[culture clash, future, space war, space colony, society, space travel, futuristic, romance, space, alien, tribe, alien planet, cgi, marine, soldier, battle, love affair, anti war, power relations, mind and soul, 3d]","[ingenious film partners, twentieth century fox film corporation, dune entertainment, lightstorm entertainment]","[sam worthington, zoe saldana, sigourney weaver, stephen lang, michelle rodriguez, giovanni ribisi, joel david moore, cch pounder, wes studi, laz alonso, dileep rao, matt gerald, sean anthony moran, jason whyte, scott lawrence, kelly kilgour, james patrick pitt, sean patrick murphy, peter dillon, kevin dorman, kelson henderson, david van horn, jacob tomuri, michael blainrozgay, jon curry, luke hawker, woody schultz, peter mensah, sonia yee, jahnel curfman, ilram choi, kyla warren, lisa roumain, debra wilson, chris mala, taylor kibby, jodie landau, julie lamm, cullen b madden, joseph brady madden, frankie torres, austin wilson, sara wilson, tamica washingtonmiller, lucy briant, nathan meister, gerry blair, matthew chamberlain, paul yates, wray wilson, james gaylyn, melvin leno clark iii, carvon futrell, brandon jelkes, micah moch, hanniyah muhammad, christopher nolen, christa oliver, april marie thomas, bravita a threatt, colin bleasdale, mike bodnar, matt clayton, nicole dionne, jamie harrison, allan henry, anthony ingruber, ashley jeffery, dean knowsley, joseph mikahunt, terry notary, kai pantano, logan pithyou, stuart pollock, raja, gareth ruck, rhian sheehan, t j storm, jodie taylor, alicia velabailey, richard whiteside, nikie zambo, julene renee]",[james cameron],"[22nd, century, paraplegic, marine, moon, pandora, unique, mission, becomes, torn, following, orders, alien, civilization, dispatched, protecting]"
1,Pirates of the Caribbean: At World's End,"[adventure, fantasy, action]","[ocean, drug abuse, exotic island, east india trading company, love of ones life, traitor, shipwreck, strong woman, ship, alliance, calypso, afterlife, fighter, pirate, swashbuckler, aftercreditsstinger]","[walt disney pictures, jerry bruckheimer films, second mate productions]","[johnny depp, orlando bloom, keira knightley, stellan skarsgård, chow yunfat, bill nighy, geoffrey rush, jack davenport, kevin mcnally, tom hollander, naomie harris, jonathan pryce, keith richards, lee arenberg, mackenzie crook, greg ellis, david bailie, martin klebba, david schofield, lauren maher, vanessa branch, angus barnett, giles new, reggie lee, dominic scott kay, takayo fischer, david meunier, hokwan tse, andy beckwith, peter donald badalamenti ii, christopher s capp, keith richards, hakeem kaekazim, ghassan massoud]",[gore verbinski],"[captain, barbossa, long, believed, come, back, elizabeth, swann, dead, life, headed, edge, earth, turner, nothing, quite, seems]"
2,Spectre,"[action, adventure, crime]","[spy, based on novel, secret agent, sequel, mi6, british secret service, united kingdom]","[columbia pictures, danjaq, b24]","[daniel craig, christoph waltz, léa seydoux, ralph fiennes, monica bellucci, ben whishaw, naomie harris, dave bautista, andrew scott, rory kinnear, jesper christensen, alessandro cremona, stephanie sigman, tenoch huerta, adriana paz, domenico fortunato, marco zingaro, stefano elfi diclaudia, ian bonar, tam williams, richard banham, pip carter, simon lenagan, alessandro bressanello, marc zinga, brigitte millar, adel bencherif, gediminas adomaitis, peppe lanzetta, francesco arca, matteo taranto, emilio aniba, benito sagredo, dai tabuchi, george lasha, sargon yelda, andy cheung, erick hayden, oleg mirochnikov, antonio salines, miloud mourad benamara, gido schimanski, nigel barber, patrice naiambana, stephane cornicard, gary fannin, sadao ueda, phillip law, wai wong, joseph balderrama, eiji mihara, junichi kajioka, victor schefé, harald windisch, tristan matthiae, detlef bothe, bodo friesecke, wilhem iben, noemi krausz, noah saavedra, francis attakpah, michael glantschnig, marlon boess, marie wohlmuth, lili epply, konstantin gerlach, lara parmiani, umit ulgen, amra mallassi, ziad abaza, walid mumuni, derek horsham, nari blairmangat, michael white, adam mcgrady, nader dernaika, pezhmaan alinia, judi dench, neve gachev, karl farrer, kim adis, maurisa selene coleman, matija mondi matović]",[sam mendes],"[bond, terrible, truth, behind, spectre, battles, political, forces, secret, service, alive, peels, back, cryptic, message, ’, past, sends, sinister, organization, trail, uncover, keep, layers, deceit, reveal]"
3,The Dark Knight Rises,"[action, crime, drama, thriller]","[dc comics, crime fighter, terrorist, secret identity, burglar, hostage drama, time bomb, gotham city, vigilante, coverup, superhero, villainess, tragic hero, terrorism, destruction, catwoman, cat burglar, imax, flood, criminal underworld, batman]","[legendary pictures, warner bros, dc entertainment, syncopy]","[christian bale, michael caine, gary oldman, anne hathaway, tom hardy, marion cotillard, joseph gordonlevitt, morgan freeman, cillian murphy, juno temple, liam neeson, matthew modine, alon aboutboul, ben mendelsohn, nestor carbonell, josh pence, tom conti, joey king, warren brown, daniel sunjata, sam kennard, aliash tepina, nick julian, miranda nolan, claire julien, aidan gillen, burn gorman, brett cullen, reggie lee, joseph lyle taylor, chris ellis, duane henry, james harvey ward, gonzalo menendez, cameron jack, lex daniel, tyler dean flores, thomas lennon, trevor white, rob brown, fredric lehne, courtney munch, chris hill, travis guba, jay benedict, will estes, david dayan fisher, glen powell, russ fega, andres perezmolina, brent briscoe, john nolan, oliver cotton, mark killeen, sarah goldberg, john macmillan, robert wisdom, ronnie gene blevins, john hollingworth, ian bohen, uri gavriel, noel gugliemi, hector atreyu ruiz, patrick cox, aramis knight, josh stewart, william devane, david gyasi, patrick jordan, joshua elijah reese, desmond harrington, mychael bates, tomas arana, peter holden, david monahan, jillian armenante, aja evans, aldous davidson, wade williams, jake canuso, massi furlan, christopher judge, patrick leahy, todd gearhart, marc abbink, isiah adams, charlie alejandro, robert arensen, grant babbitt, fileena bahris, rick bolander, kyle patrick brennan, scott churchson, bill cowher, graham curry, stephanie domini ehlert, john farrer, frank fata, christopher bryan gomez, vito grassi, ...]",[christopher nolan],"[attorney, gotham, dent, batman, city, district, harvey, police, department, assumes, responsibility, eight, years, later, mysterious, selina, kyle, new, terrorist, leader, dark, knight, resurfaces, protect, late, subsequently, hunted, encounters, villainous, bane]"
4,John Carter,"[action, adventure, science fiction]","[based on novel, mars, medallion, space travel, princess, alien, steampunk, martian, escape, edgar rice burroughs, alien race, superhuman strength, mars civilization, sword and planet, 19th century, 3d]",[walt disney pictures],"[taylor kitsch, lynn collins, samantha morton, willem dafoe, thomas haden church, mark strong, ciarán hinds, dominic west, james purefoy, bryan cranston, polly walker, daryl sabara, arkie reece, davood ghadami, pippa nixon, james embree, philip philmar, emily tierney, edmund kente, nicholas woodeson, kyle agnew, don stark, josh daugherty, jared cyr, christopher goodman, amanda clayton, joseph billingiere]",[andrew stanton],"[carter, former, military, captain, reluctantly, becomes, embroiled, john, inexplicably, transported, exotic, planet, barsoom, epic, conflict, rediscovers, people, rests, war, weary, mysterious, mars, world, brink, collapse, humanity, realizes, survival, hands]"

In [ ]:
# The feature 'keywords' may contain stopwords, since the elements are phrases instead of names
# I need to tokenize each element of each list, then I will remove stopwords

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

def remove_stopwords(mylist):
    stop_words = set(stopwords.words('english'))
    newlist = []
    for element in mylist:
        words = word_tokenize(element)
        filtered_words = [word for word in words if word not in stop_words]
        newlist.append(' '.join(filtered_words))
    return newlist

In [ ]:
clean1_df['keywords_list'] = clean1_df['keywords_list'].apply(remove_stopwords)
clean1_df.head()

,title,genres_list,keywords_list,prod_companies_list,cast_list,director_list,overview_key_list
0,Avatar,"[action, adventure, fantasy, science fiction]","[culture clash, future, space war, space colony, society, space travel, futuristic, romance, space, alien, tribe, alien planet, cgi, marine, soldier, battle, love affair, anti war, power relations, mind soul, 3d]","[ingenious film partners, twentieth century fox film corporation, dune entertainment, lightstorm entertainment]","[sam worthington, zoe saldana, sigourney weaver, stephen lang, michelle rodriguez, giovanni ribisi, joel david moore, cch pounder, wes studi, laz alonso, dileep rao, matt gerald, sean anthony moran, jason whyte, scott lawrence, kelly kilgour, james patrick pitt, sean patrick murphy, peter dillon, kevin dorman, kelson henderson, david van horn, jacob tomuri, michael blainrozgay, jon curry, luke hawker, woody schultz, peter mensah, sonia yee, jahnel curfman, ilram choi, kyla warren, lisa roumain, debra wilson, chris mala, taylor kibby, jodie landau, julie lamm, cullen b madden, joseph brady madden, frankie torres, austin wilson, sara wilson, tamica washingtonmiller, lucy briant, nathan meister, gerry blair, matthew chamberlain, paul yates, wray wilson, james gaylyn, melvin leno clark iii, carvon futrell, brandon jelkes, micah moch, hanniyah muhammad, christopher nolen, christa oliver, april marie thomas, bravita a threatt, colin bleasdale, mike bodnar, matt clayton, nicole dionne, jamie harrison, allan henry, anthony ingruber, ashley jeffery, dean knowsley, joseph mikahunt, terry notary, kai pantano, logan pithyou, stuart pollock, raja, gareth ruck, rhian sheehan, t j storm, jodie taylor, alicia velabailey, richard whiteside, nikie zambo, julene renee]",[james cameron],"[22nd, century, paraplegic, marine, moon, pandora, unique, mission, becomes, torn, following, orders, alien, civilization, dispatched, protecting]"
1,Pirates of the Caribbean: At World's End,"[adventure, fantasy, action]","[ocean, drug abuse, exotic island, east india trading company, love ones life, traitor, shipwreck, strong woman, ship, alliance, calypso, afterlife, fighter, pirate, swashbuckler, aftercreditsstinger]","[walt disney pictures, jerry bruckheimer films, second mate productions]","[johnny depp, orlando bloom, keira knightley, stellan skarsgård, chow yunfat, bill nighy, geoffrey rush, jack davenport, kevin mcnally, tom hollander, naomie harris, jonathan pryce, keith richards, lee arenberg, mackenzie crook, greg ellis, david bailie, martin klebba, david schofield, lauren maher, vanessa branch, angus barnett, giles new, reggie lee, dominic scott kay, takayo fischer, david meunier, hokwan tse, andy beckwith, peter donald badalamenti ii, christopher s capp, keith richards, hakeem kaekazim, ghassan massoud]",[gore verbinski],"[captain, barbossa, long, believed, come, back, elizabeth, swann, dead, life, headed, edge, earth, turner, nothing, quite, seems]"
2,Spectre,"[action, adventure, crime]","[spy, based novel, secret agent, sequel, mi6, british secret service, united kingdom]","[columbia pictures, danjaq, b24]","[daniel craig, christoph waltz, léa seydoux, ralph fiennes, monica bellucci, ben whishaw, naomie harris, dave bautista, andrew scott, rory kinnear, jesper christensen, alessandro cremona, stephanie sigman, tenoch huerta, adriana paz, domenico fortunato, marco zingaro, stefano elfi diclaudia, ian bonar, tam williams, richard banham, pip carter, simon lenagan, alessandro bressanello, marc zinga, brigitte millar, adel bencherif, gediminas adomaitis, peppe lanzetta, francesco arca, matteo taranto, emilio aniba, benito sagredo, dai tabuchi, george lasha, sargon yelda, andy cheung, erick hayden, oleg mirochnikov, antonio salines, miloud mourad benamara, gido schimanski, nigel barber, patrice naiambana, stephane cornicard, gary fannin, sadao ueda, phillip law, wai wong, joseph balderrama, eiji mihara, junichi kajioka, victor schefé, harald windisch, tristan matthiae, detlef bothe, bodo friesecke, wilhem iben, noemi krausz, noah saavedra, francis attakpah, michael glantschnig, marlon boess, marie wohlmuth, lili epply, konstantin gerlach, lara parmiani, umit ulgen, amra mallassi, ziad abaza, walid mumuni, derek horsham, nari blairmangat, michael white, adam mcgrady, nader dernaika, pezhmaan alinia, judi dench, neve gachev, karl farrer, kim adis, maurisa selene coleman, matija mondi matović]",[sam mendes],"[bond, terrible, truth, behind, spectre, battles, political, forces, secret, service, alive, peels, back, cryptic, message, ’, past, sends, sinister, organization, trail, uncover, keep, layers, deceit, reveal]"
3,The Dark Knight Rises,"[action, crime, drama, thriller]","[dc comics, crime fighter, terrorist, secret identity, burglar, hostage drama, time bomb, gotham city, vigilante, coverup, superhero, villainess, tragic hero, terrorism, destruction, catwoman, cat burglar, imax, flood, criminal underworld, batman]","[legendary pictures, warner bros, dc entertainment, syncopy]","[christian bale, michael caine, gary oldman, anne hathaway, tom hardy, marion cotillard, joseph gordonlevitt, morgan freeman, cillian murphy, juno temple, liam neeson, matthew modine, alon aboutboul, ben mendelsohn, nestor carbonell, josh pence, tom conti, joey king, warren brown, daniel sunjata, sam kennard, aliash tepina, nick julian, miranda nolan, claire julien, aidan gillen, burn gorman, brett cullen, reggie lee, joseph lyle taylor, chris ellis, duane henry, james harvey ward, gonzalo menendez, cameron jack, lex daniel, tyler dean flores, thomas lennon, trevor white, rob brown, fredric lehne, courtney munch, chris hill, travis guba, jay benedict, will estes, david dayan fisher, glen powell, russ fega, andres perezmolina, brent briscoe, john nolan, oliver cotton, mark killeen, sarah goldberg, john macmillan, robert wisdom, ronnie gene blevins, john hollingworth, ian bohen, uri gavriel, noel gugliemi, hector atreyu ruiz, patrick cox, aramis knight, josh stewart, william devane, david gyasi, patrick jordan, joshua elijah reese, desmond harrington, mychael bates, tomas arana, peter holden, david monahan, jillian armenante, aja evans, aldous davidson, wade williams, jake canuso, massi furlan, christopher judge, patrick leahy, todd gearhart, marc abbink, isiah adams, charlie alejandro, robert arensen, grant babbitt, fileena bahris, rick bolander, kyle patrick brennan, scott churchson, bill cowher, graham curry, stephanie domini ehlert, john farrer, frank fata, christopher bryan gomez, vito grassi, ...]",[christopher nolan],"[attorney, gotham, dent, batman, city, district, harvey, police, department, assumes, responsibility, eight, years, later, mysterious, selina, kyle, new, terrorist, leader, dark, knight, resurfaces, protect, late, subsequently, hunted, encounters, villainous, bane]"
4,John Carter,"[action, adventure, science fiction]","[based novel, mars, medallion, space travel, princess, alien, steampunk, martian, escape, edgar rice burroughs, alien race, superhuman strength, mars civilization, sword planet, 19th century, 3d]",[walt disney pictures],"[taylor kitsch, lynn collins, samantha morton, willem dafoe, thomas haden church, mark strong, ciarán hinds, dominic west, james purefoy, bryan cranston, polly walker, daryl sabara, arkie reece, davood ghadami, pippa nixon, james embree, philip philmar, emily tierney, edmund kente, nicholas woodeson, kyle agnew, don stark, josh daugherty, jared cyr, christopher goodman, amanda clayton, joseph billingiere]",[andrew stanton],"[carter, former, military, captain, reluctantly, becomes, embroiled, john, inexplicably, transported, exotic, planet, barsoom, epic, conflict, rediscovers, people, rests, war, weary, mysterious, mars, world, brink, collapse, humanity, realizes, survival, hands]"

In [ ]:
## Each element of each lists are strings. We will remove spaces to create a unique string.
## e.g. 'tom sawyer' and 'tom kitsch' have similarities, but 'tomsawyer' and 'tomkitsch' are distinct.

def remove_space(mylist):
    newlist = []
    newlist = [element.replace(' ', '') for element in mylist]
    return newlist

In [ ]:
# Apply function to remove space from all elements, for 'prod_companies_list' , 'cast_list' , 'director_list' features
# unnecessary for 'overview' feature

clean1_df[['genres_list','keywords_list','prod_companies_list','cast_list','director_list']] = clean1_df[[ \
            'genres_list','keywords_list','prod_companies_list','cast_list','director_list']].applymap(remove_space)
clean1_df.head()

,title,genres_list,keywords_list,prod_companies_list,cast_list,director_list,overview_key_list
0,Avatar,"[action, adventure, fantasy, sciencefiction]","[cultureclash, future, spacewar, spacecolony, society, spacetravel, futuristic, romance, space, alien, tribe, alienplanet, cgi, marine, soldier, battle, loveaffair, antiwar, powerrelations, mindsoul, 3d]","[ingeniousfilmpartners, twentiethcenturyfoxfilmcorporation, duneentertainment, lightstormentertainment]","[samworthington, zoesaldana, sigourneyweaver, stephenlang, michellerodriguez, giovanniribisi, joeldavidmoore, cchpounder, wesstudi, lazalonso, dileeprao, mattgerald, seananthonymoran, jasonwhyte, scottlawrence, kellykilgour, jamespatrickpitt, seanpatrickmurphy, peterdillon, kevindorman, kelsonhenderson, davidvanhorn, jacobtomuri, michaelblainrozgay, joncurry, lukehawker, woodyschultz, petermensah, soniayee, jahnelcurfman, ilramchoi, kylawarren, lisaroumain, debrawilson, chrismala, taylorkibby, jodielandau, julielamm, cullenbmadden, josephbradymadden, frankietorres, austinwilson, sarawilson, tamicawashingtonmiller, lucybriant, nathanmeister, gerryblair, matthewchamberlain, paulyates, wraywilson, jamesgaylyn, melvinlenoclarkiii, carvonfutrell, brandonjelkes, micahmoch, hanniyahmuhammad, christophernolen, christaoliver, aprilmariethomas, bravitaathreatt, colinbleasdale, mikebodnar, mattclayton, nicoledionne, jamieharrison, allanhenry, anthonyingruber, ashleyjeffery, deanknowsley, josephmikahunt, terrynotary, kaipantano, loganpithyou, stuartpollock, raja, garethruck, rhiansheehan, tjstorm, jodietaylor, aliciavelabailey, richardwhiteside, nikiezambo, julenerenee]",[jamescameron],"[22nd, century, paraplegic, marine, moon, pandora, unique, mission, becomes, torn, following, orders, alien, civilization, dispatched, protecting]"
1,Pirates of the Caribbean: At World's End,"[adventure, fantasy, action]","[ocean, drugabuse, exoticisland, eastindiatradingcompany, loveoneslife, traitor, shipwreck, strongwoman, ship, alliance, calypso, afterlife, fighter, pirate, swashbuckler, aftercreditsstinger]","[waltdisneypictures, jerrybruckheimerfilms, secondmateproductions]","[johnnydepp, orlandobloom, keiraknightley, stellanskarsgård, chowyunfat, billnighy, geoffreyrush, jackdavenport, kevinmcnally, tomhollander, naomieharris, jonathanpryce, keithrichards, leearenberg, mackenziecrook, gregellis, davidbailie, martinklebba, davidschofield, laurenmaher, vanessabranch, angusbarnett, gilesnew, reggielee, dominicscottkay, takayofischer, davidmeunier, hokwantse, andybeckwith, peterdonaldbadalamentiii, christopherscapp, keithrichards, hakeemkaekazim, ghassanmassoud]",[goreverbinski],"[captain, barbossa, long, believed, come, back, elizabeth, swann, dead, life, headed, edge, earth, turner, nothing, quite, seems]"
2,Spectre,"[action, adventure, crime]","[spy, basednovel, secretagent, sequel, mi6, britishsecretservice, unitedkingdom]","[columbiapictures, danjaq, b24]","[danielcraig, christophwaltz, léaseydoux, ralphfiennes, monicabellucci, benwhishaw, naomieharris, davebautista, andrewscott, rorykinnear, jesperchristensen, alessandrocremona, stephaniesigman, tenochhuerta, adrianapaz, domenicofortunato, marcozingaro, stefanoelfidiclaudia, ianbonar, tamwilliams, richardbanham, pipcarter, simonlenagan, alessandrobressanello, marczinga, brigittemillar, adelbencherif, gediminasadomaitis, peppelanzetta, francescoarca, matteotaranto, emilioaniba, benitosagredo, daitabuchi, georgelasha, sargonyelda, andycheung, erickhayden, olegmirochnikov, antoniosalines, miloudmouradbenamara, gidoschimanski, nigelbarber, patricenaiambana, stephanecornicard, garyfannin, sadaoueda, philliplaw, waiwong, josephbalderrama, eijimihara, junichikajioka, victorschefé, haraldwindisch, tristanmatthiae, detlefbothe, bodofriesecke, wilhemiben, noemikrausz, noahsaavedra, francisattakpah, michaelglantschnig, marlonboess, mariewohlmuth, liliepply, konstantingerlach, laraparmiani, umitulgen, amramallassi, ziadabaza, walidmumuni, derekhorsham, nariblairmangat, michaelwhite, adammcgrady, naderdernaika, pezhmaanalinia, judidench, nevegachev, karlfarrer, kimadis, maurisaselenecoleman, matijamondimatović]",[sammendes],"[bond, terrible, truth, behind, spectre, battles, political, forces, secret, service, alive, peels, back, cryptic, message, ’, past, sends, sinister, organization, trail, uncover, keep, layers, deceit, reveal]"
3,The Dark Knight Rises,"[action, crime, drama, thriller]","[dccomics, crimefighter, terrorist, secretidentity, burglar, hostagedrama, timebomb, gothamcity, vigilante, coverup, superhero, villainess, tragichero, terrorism, destruction, catwoman, catburglar, imax, flood, criminalunderworld, batman]","[legendarypictures, warnerbros, dcentertainment, syncopy]","[christianbale, michaelcaine, garyoldman, annehathaway, tomhardy, marioncotillard, josephgordonlevitt, morganfreeman, cillianmurphy, junotemple, liamneeson, matthewmodine, alonaboutboul, benmendelsohn, nestorcarbonell, joshpence, tomconti, joeyking, warrenbrown, danielsunjata, samkennard, aliashtepina, nickjulian, mirandanolan, clairejulien, aidangillen, burngorman, brettcullen, reggielee, josephlyletaylor, chrisellis, duanehenry, jamesharveyward, gonzalomenendez, cameronjack, lexdaniel, tylerdeanflores, thomaslennon, trevorwhite, robbrown, fredriclehne, courtneymunch, chrishill, travisguba, jaybenedict, willestes, daviddayanfisher, glenpowell, russfega, andresperezmolina, brentbriscoe, johnnolan, olivercotton, markkilleen, sarahgoldberg, johnmacmillan, robertwisdom, ronniegeneblevins, johnhollingworth, ianbohen, urigavriel, noelgugliemi, hectoratreyuruiz, patrickcox, aramisknight, joshstewart, williamdevane, davidgyasi, patrickjordan, joshuaelijahreese, desmondharrington, mychaelbates, tomasarana, peterholden, davidmonahan, jillianarmenante, ajaevans, aldousdavidson, wadewilliams, jakecanuso, massifurlan, christopherjudge, patrickleahy, toddgearhart, marcabbink, isiahadams, charliealejandro, robertarensen, grantbabbitt, fileenabahris, rickbolander, kylepatrickbrennan, scottchurchson, billcowher, grahamcurry, stephaniedominiehlert, johnfarrer, frankfata, christopherbryangomez, vitograssi, ...]",[christophernolan],"[attorney, gotham, dent, batman, city, district, harvey, police, department, assumes, responsibility, eight, years, later, mysterious, selina, kyle, new, terrorist, leader, dark, knight, resurfaces, protect, late, subsequently, hunted, encounters, villainous, bane]"
4,John Carter,"[action, adventure, sciencefiction]","[basednovel, mars, medallion, spacetravel, princess, alien, steampunk, martian, escape, edgarriceburroughs, alienrace, superhumanstrength, marscivilization, swordplanet, 19thcentury, 3d]",[waltdisneypictures],"[taylorkitsch, lynncollins, samanthamorton, willemdafoe, thomashadenchurch, markstrong, ciaránhinds, dominicwest, jamespurefoy, bryancranston, pollywalker, darylsabara, arkiereece, davoodghadami, pippanixon, jamesembree, philipphilmar, emilytierney, edmundkente, nicholaswoodeson, kyleagnew, donstark, joshdaugherty, jaredcyr, christophergoodman, amandaclayton, josephbillingiere]",[andrewstanton],"[carter, former, military, captain, reluctantly, becomes, embroiled, john, inexplicably, transported, exotic, planet, barsoom, epic, conflict, rediscovers, people, rests, war, weary, mysterious, mars, world, brink, collapse, humanity, realizes, survival, hands]"

In [ ]:
# Now that unique values are merged into one string each, I will be using only unigrams for the TF-IDF vectorizer.

### Tokenization

In [ ]:
# The elements of the feature 'release_date' is in yyyy-mm-dd format. We will isolate yyyy.

from nltk.tokenize import RegexpTokenizer
tokenizer = RegexpTokenizer(r'\w+')

In [ ]:
## first, tokenize
clean1_df['year'] = movies_df['release_date'].apply(lambda x: tokenizer.tokenize(x) )
clean1_df[['year']].head()

             year
0  [2009, 12, 10]
1  [2007, 05, 19]
2  [2015, 10, 26]
3  [2012, 07, 16]
4  [2012, 03, 07]

In [ ]:
## delete 2nd and 3rd element from each list, to retain only year
for i in range(0,len(clean1_df)):
    del clean1_df['year'][i][1:3]
    
clean1_df[['year']].head()

     year
0  [2009]
1  [2007]
2  [2015]
3  [2012]
4  [2012]

### Lemmatization

In [ ]:
wn = nltk.WordNetLemmatizer()

# Creating function to apply lematizer
def lemmatize(tokenized_text):
    text = [wn.lemmatize(word) for word in tokenized_text]
    return text

In [ ]:
# Applying the Lemmatizer
clean1_df['overview_key_list'] = clean1_df['overview_key_list'].apply(lemmatize)

In [ ]:
clean1_df[['overview_key_list']].head()

                                                                                                                                                                                                                                                         overview_key_list
0                                                                                                                        [22nd, century, paraplegic, marine, moon, pandora, unique, mission, becomes, torn, following, order, alien, civilization, dispatched, protecting]
1                                                                                                                                        [captain, barbossa, long, believed, come, back, elizabeth, swann, dead, life, headed, edge, earth, turner, nothing, quite, seems]
2                                                            [bond, terrible, truth, behind, spectre, battle, political, force, secret, service, alive, peel, back, cryptic, message, ’, past, sends, sinister, organization, trail, uncover, keep, layer, deceit, reveal]
3  [attorney, gotham, dent, batman, city, district, harvey, police, department, assumes, responsibility, eight, year, later, mysterious, selina, kyle, new, terrorist, leader, dark, knight, resurfaces, protect, late, subsequently, hunted, encounter, villainous, bane]
4       [carter, former, military, captain, reluctantly, becomes, embroiled, john, inexplicably, transported, exotic, planet, barsoom, epic, conflict, rediscovers, people, rest, war, weary, mysterious, mar, world, brink, collapse, humanity, realizes, survival, hand]

In [ ]:
# Add 'original_language' feature to clean dataframe while maintaining elements in list format for consistency
clean1_df['language'] = movies_df['original_language'].apply(lambda x: [x])
clean1_df.head()

,title,genres_list,keywords_list,prod_companies_list,cast_list,director_list,overview_key_list,year,language
0,Avatar,"[action, adventure, fantasy, sciencefiction]","[cultureclash, future, spacewar, spacecolony, society, spacetravel, futuristic, romance, space, alien, tribe, alienplanet, cgi, marine, soldier, battle, loveaffair, antiwar, powerrelations, mindsoul, 3d]","[ingeniousfilmpartners, twentiethcenturyfoxfilmcorporation, duneentertainment, lightstormentertainment]","[samworthington, zoesaldana, sigourneyweaver, stephenlang, michellerodriguez, giovanniribisi, joeldavidmoore, cchpounder, wesstudi, lazalonso, dileeprao, mattgerald, seananthonymoran, jasonwhyte, scottlawrence, kellykilgour, jamespatrickpitt, seanpatrickmurphy, peterdillon, kevindorman, kelsonhenderson, davidvanhorn, jacobtomuri, michaelblainrozgay, joncurry, lukehawker, woodyschultz, petermensah, soniayee, jahnelcurfman, ilramchoi, kylawarren, lisaroumain, debrawilson, chrismala, taylorkibby, jodielandau, julielamm, cullenbmadden, josephbradymadden, frankietorres, austinwilson, sarawilson, tamicawashingtonmiller, lucybriant, nathanmeister, gerryblair, matthewchamberlain, paulyates, wraywilson, jamesgaylyn, melvinlenoclarkiii, carvonfutrell, brandonjelkes, micahmoch, hanniyahmuhammad, christophernolen, christaoliver, aprilmariethomas, bravitaathreatt, colinbleasdale, mikebodnar, mattclayton, nicoledionne, jamieharrison, allanhenry, anthonyingruber, ashleyjeffery, deanknowsley, josephmikahunt, terrynotary, kaipantano, loganpithyou, stuartpollock, raja, garethruck, rhiansheehan, tjstorm, jodietaylor, aliciavelabailey, richardwhiteside, nikiezambo, julenerenee]",[jamescameron],"[22nd, century, paraplegic, marine, moon, pandora, unique, mission, becomes, torn, following, order, alien, civilization, dispatched, protecting]",[2009],[en]
1,Pirates of the Caribbean: At World's End,"[adventure, fantasy, action]","[ocean, drugabuse, exoticisland, eastindiatradingcompany, loveoneslife, traitor, shipwreck, strongwoman, ship, alliance, calypso, afterlife, fighter, pirate, swashbuckler, aftercreditsstinger]","[waltdisneypictures, jerrybruckheimerfilms, secondmateproductions]","[johnnydepp, orlandobloom, keiraknightley, stellanskarsgård, chowyunfat, billnighy, geoffreyrush, jackdavenport, kevinmcnally, tomhollander, naomieharris, jonathanpryce, keithrichards, leearenberg, mackenziecrook, gregellis, davidbailie, martinklebba, davidschofield, laurenmaher, vanessabranch, angusbarnett, gilesnew, reggielee, dominicscottkay, takayofischer, davidmeunier, hokwantse, andybeckwith, peterdonaldbadalamentiii, christopherscapp, keithrichards, hakeemkaekazim, ghassanmassoud]",[goreverbinski],"[captain, barbossa, long, believed, come, back, elizabeth, swann, dead, life, headed, edge, earth, turner, nothing, quite, seems]",[2007],[en]
2,Spectre,"[action, adventure, crime]","[spy, basednovel, secretagent, sequel, mi6, britishsecretservice, unitedkingdom]","[columbiapictures, danjaq, b24]","[danielcraig, christophwaltz, léaseydoux, ralphfiennes, monicabellucci, benwhishaw, naomieharris, davebautista, andrewscott, rorykinnear, jesperchristensen, alessandrocremona, stephaniesigman, tenochhuerta, adrianapaz, domenicofortunato, marcozingaro, stefanoelfidiclaudia, ianbonar, tamwilliams, richardbanham, pipcarter, simonlenagan, alessandrobressanello, marczinga, brigittemillar, adelbencherif, gediminasadomaitis, peppelanzetta, francescoarca, matteotaranto, emilioaniba, benitosagredo, daitabuchi, georgelasha, sargonyelda, andycheung, erickhayden, olegmirochnikov, antoniosalines, miloudmouradbenamara, gidoschimanski, nigelbarber, patricenaiambana, stephanecornicard, garyfannin, sadaoueda, philliplaw, waiwong, josephbalderrama, eijimihara, junichikajioka, victorschefé, haraldwindisch, tristanmatthiae, detlefbothe, bodofriesecke, wilhemiben, noemikrausz, noahsaavedra, francisattakpah, michaelglantschnig, marlonboess, mariewohlmuth, liliepply, konstantingerlach, laraparmiani, umitulgen, amramallassi, ziadabaza, walidmumuni, derekhorsham, nariblairmangat, michaelwhite, adammcgrady, naderdernaika, pezhmaanalinia, judidench, nevegachev, karlfarrer, kimadis, maurisaselenecoleman, matijamondimatović]",[sammendes],"[bond, terrible, truth, behind, spectre, battle, political, force, secret, service, alive, peel, back, cryptic, message, ’, past, sends, sinister, organization, trail, uncover, keep, layer, deceit, reveal]",[2015],[en]
3,The Dark Knight Rises,"[action, crime, drama, thriller]","[dccomics, crimefighter, terrorist, secretidentity, burglar, hostagedrama, timebomb, gothamcity, vigilante, coverup, superhero, villainess, tragichero, terrorism, destruction, catwoman, catburglar, imax, flood, criminalunderworld, batman]","[legendarypictures, warnerbros, dcentertainment, syncopy]","[christianbale, michaelcaine, garyoldman, annehathaway, tomhardy, marioncotillard, josephgordonlevitt, morganfreeman, cillianmurphy, junotemple, liamneeson, matthewmodine, alonaboutboul, benmendelsohn, nestorcarbonell, joshpence, tomconti, joeyking, warrenbrown, danielsunjata, samkennard, aliashtepina, nickjulian, mirandanolan, clairejulien, aidangillen, burngorman, brettcullen, reggielee, josephlyletaylor, chrisellis, duanehenry, jamesharveyward, gonzalomenendez, cameronjack, lexdaniel, tylerdeanflores, thomaslennon, trevorwhite, robbrown, fredriclehne, courtneymunch, chrishill, travisguba, jaybenedict, willestes, daviddayanfisher, glenpowell, russfega, andresperezmolina, brentbriscoe, johnnolan, olivercotton, markkilleen, sarahgoldberg, johnmacmillan, robertwisdom, ronniegeneblevins, johnhollingworth, ianbohen, urigavriel, noelgugliemi, hectoratreyuruiz, patrickcox, aramisknight, joshstewart, williamdevane, davidgyasi, patrickjordan, joshuaelijahreese, desmondharrington, mychaelbates, tomasarana, peterholden, davidmonahan, jillianarmenante, ajaevans, aldousdavidson, wadewilliams, jakecanuso, massifurlan, christopherjudge, patrickleahy, toddgearhart, marcabbink, isiahadams, charliealejandro, robertarensen, grantbabbitt, fileenabahris, rickbolander, kylepatrickbrennan, scottchurchson, billcowher, grahamcurry, stephaniedominiehlert, johnfarrer, frankfata, christopherbryangomez, vitograssi, ...]",[christophernolan],"[attorney, gotham, dent, batman, city, district, harvey, police, department, assumes, responsibility, eight, year, later, mysterious, selina, kyle, new, terrorist, leader, dark, knight, resurfaces, protect, late, subsequently, hunted, encounter, villainous, bane]",[2012],[en]
4,John Carter,"[action, adventure, sciencefiction]","[basednovel, mars, medallion, spacetravel, princess, alien, steampunk, martian, escape, edgarriceburroughs, alienrace, superhumanstrength, marscivilization, swordplanet, 19thcentury, 3d]",[waltdisneypictures],"[taylorkitsch, lynncollins, samanthamorton, willemdafoe, thomashadenchurch, markstrong, ciaránhinds, dominicwest, jamespurefoy, bryancranston, pollywalker, darylsabara, arkiereece, davoodghadami, pippanixon, jamesembree, philipphilmar, emilytierney, edmundkente, nicholaswoodeson, kyleagnew, donstark, joshdaugherty, jaredcyr, christophergoodman, amandaclayton, josephbillingiere]",[andrewstanton],"[carter, former, military, captain, reluctantly, becomes, embroiled, john, inexplicably, transported, exotic, planet, barsoom, epic, conflict, rediscovers, people, rest, war, weary, mysterious, mar, world, brink, collapse, humanity, realizes, survival, hand]",[2012],[en]

## Vectorizer: TF-IDF (Word Embeddings)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Instantiate TF-IDF vectorizer
# ngram_range: default to unigrams
tf = TfidfVectorizer()

In [ ]:
# create dataframe without the movie titles
df = clean1_df.drop('title', axis=1)

# convert list elements to strings
df = df.applymap(lambda x: ' '.join(x))
df.head()

,genres_list,keywords_list,prod_companies_list,cast_list,director_list,overview_key_list,year,language
0,action adventure fantasy sciencefiction,cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindsoul 3d,ingeniousfilmpartners twentiethcenturyfoxfilmcorporation duneentertainment lightstormentertainment,samworthington zoesaldana sigourneyweaver stephenlang michellerodriguez giovanniribisi joeldavidmoore cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyte scottlawrence kellykilgour jamespatrickpitt seanpatrickmurphy peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblainrozgay joncurry lukehawker woodyschultz petermensah soniayee jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibby jodielandau julielamm cullenbmadden josephbradymadden frankietorres austinwilson sarawilson tamicawashingtonmiller lucybriant nathanmeister gerryblair matthewchamberlain paulyates wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrell brandonjelkes micahmoch hanniyahmuhammad christophernolen christaoliver aprilmariethomas bravitaathreatt colinbleasdale mikebodnar mattclayton nicoledionne jamieharrison allanhenry anthonyingruber ashleyjeffery deanknowsley josephmikahunt terrynotary kaipantano loganpithyou stuartpollock raja garethruck rhiansheehan tjstorm jodietaylor aliciavelabailey richardwhiteside nikiezambo julenerenee,jamescameron,22nd century paraplegic marine moon pandora unique mission becomes torn following order alien civilization dispatched protecting,2009,en
1,adventure fantasy action,ocean drugabuse exoticisland eastindiatradingcompany loveoneslife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger,waltdisneypictures jerrybruckheimerfilms secondmateproductions,johnnydepp orlandobloom keiraknightley stellanskarsgård chowyunfat billnighy geoffreyrush jackdavenport kevinmcnally tomhollander naomieharris jonathanpryce keithrichards leearenberg mackenziecrook gregellis davidbailie martinklebba davidschofield laurenmaher vanessabranch angusbarnett gilesnew reggielee dominicscottkay takayofischer davidmeunier hokwantse andybeckwith peterdonaldbadalamentiii christopherscapp keithrichards hakeemkaekazim ghassanmassoud,goreverbinski,captain barbossa long believed come back elizabeth swann dead life headed edge earth turner nothing quite seems,2007,en
2,action adventure crime,spy basednovel secretagent sequel mi6 britishsecretservice unitedkingdom,columbiapictures danjaq b24,danielcraig christophwaltz léaseydoux ralphfiennes monicabellucci benwhishaw naomieharris davebautista andrewscott rorykinnear jesperchristensen alessandrocremona stephaniesigman tenochhuerta adrianapaz domenicofortunato marcozingaro stefanoelfidiclaudia ianbonar tamwilliams richardbanham pipcarter simonlenagan alessandrobressanello marczinga brigittemillar adelbencherif gediminasadomaitis peppelanzetta francescoarca matteotaranto emilioaniba benitosagredo daitabuchi georgelasha sargonyelda andycheung erickhayden olegmirochnikov antoniosalines miloudmouradbenamara gidoschimanski nigelbarber patricenaiambana stephanecornicard garyfannin sadaoueda philliplaw waiwong josephbalderrama eijimihara junichikajioka victorschefé haraldwindisch tristanmatthiae detlefbothe bodofriesecke wilhemiben noemikrausz noahsaavedra francisattakpah michaelglantschnig marlonboess mariewohlmuth liliepply konstantingerlach laraparmiani umitulgen amramallassi ziadabaza walidmumuni derekhorsham nariblairmangat michaelwhite adammcgrady naderdernaika pezhmaanalinia judidench nevegachev karlfarrer kimadis maurisaselenecoleman matijamondimatović,sammendes,bond terrible truth behind spectre battle political force secret service alive peel back cryptic message ’ past sends sinister organization trail uncover keep layer deceit reveal,2015,en
3,action crime drama thriller,dccomics crimefighter terrorist secretidentity burglar hostagedrama timebomb gothamcity vigilante coverup superhero villainess tragichero terrorism destruction catwoman catburglar imax flood criminalunderworld batman,legendarypictures warnerbros dcentertainment syncopy,christianbale michaelcaine garyoldman annehathaway tomhardy marioncotillard josephgordonlevitt morganfreeman cillianmurphy junotemple liamneeson matthewmodine alonaboutboul benmendelsohn nestorcarbonell joshpence tomconti joeyking warrenbrown danielsunjata samkennard aliashtepina nickjulian mirandanolan clairejulien aidangillen burngorman brettcullen reggielee josephlyletaylor chrisellis duanehenry jamesharveyward gonzalomenendez cameronjack lexdaniel tylerdeanflores thomaslennon trevorwhite robbrown fredriclehne courtneymunch chrishill travisguba jaybenedict willestes daviddayanfisher glenpowell russfega andresperezmolina brentbriscoe johnnolan olivercotton markkilleen sarahgoldberg johnmacmillan robertwisdom ronniegeneblevins johnhollingworth ianbohen urigavriel noelgugliemi hectoratreyuruiz patrickcox aramisknight joshstewart williamdevane davidgyasi patrickjordan joshuaelijahreese desmondharrington mychaelbates tomasarana peterholden davidmonahan jillianarmenante ajaevans aldousdavidson wadewilliams jakecanuso massifurlan christopherjudge patrickleahy toddgearhart marcabbink isiahadams charliealejandro robertarensen grantbabbitt fileenabahris rickbolander kylepatrickbrennan scottchurchson billcowher grahamcurry stephaniedominiehlert johnfarrer frankfata christopherbryangomez vitograssi michaelwrengucciardo samharris edheavey johnwiwanonkiw cindyjackson danieljordano williamkania tiffanykemp sunjaekim hrvojeklecz alexkruz tylerlamarr lejon pauljudeletersky joelipari silvialombardo jorgemardel calemcconnell daviddalemccue tiffanysandermckenzie allenmerritt olanmontgomery alexmoore shanenolan jacksonnunn josephobrien michaelpapajohn salomonpassariello kyledavidpierce troypolamalu michaelpower jamesrawlings kirstenroeters benroethlisberger markroman anthonyjsacco ericsalazar emilyschooley thomastull chrisvaina vincentvanommen michellevezzani barbaravincent justinmichaelwoods jasonyee mariazambrana johnzion alexziwak tommybayiokos matthewgooley jeffmoffitt markfalvo diogohausen garysievers orionmccabe londonmay jamesquinn danielnewman,christophernolan,attorney gotham dent batman city district harvey police department assumes responsibility eight year later mysterious selina kyle new terrorist leader dark knight resurfaces protect late subsequently hunted encounter villainous bane,2012,en
4,action adventure sciencefiction,basednovel mars medallion spacetravel princess alien steampunk martian escape edgarriceburroughs alienrace superhumanstrength marscivilization swordplanet 19thcentury 3d,waltdisneypictures,taylorkitsch lynncollins samanthamorton willemdafoe thomashadenchurch markstrong ciaránhinds dominicwest jamespurefoy bryancranston pollywalker darylsabara arkiereece davoodghadami pippanixon jamesembree philipphilmar emilytierney edmundkente nicholaswoodeson kyleagnew donstark joshdaugherty jaredcyr christophergoodman amandaclayton josephbillingiere,andrewstanton,carter former military captain reluctantly becomes embroiled john inexplicably transported exotic planet barsoom epic conflict rediscovers people rest war weary mysterious mar world brink collapse humanity realizes survival hand,2012,en

In [ ]:
# merge the strings into a single string for each row
merge = df.apply(lambda x: ' '.join(x), axis=1)
merge.head()

0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          action adventure fantasy sciencefiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindsoul 3d ingeniousfilmpartners twentiethcenturyfoxfilmcorporation duneentertainment lightstormentertainment samworthington zoesaldana sigourneyweaver stephenlang michellerodriguez giovanniribisi joeldavidmoore cchpounder wesstudi lazalonso dileeprao mattgerald seananthonymoran jasonwhyte scottlawrence kellykilgour jamespatrickpitt seanpatrickmurphy peterdillon kevindorman kelsonhenderson davidvanhorn jacobtomuri michaelblainrozgay joncurry lukehawker woodyschultz petermensah soniayee jahnelcurfman ilramchoi kylawarren lisaroumain debrawilson chrismala taylorkibby jodielandau julielamm cullenbmadden josephbradymadden frankietorres austinwilson sarawilson tamicawashingtonmiller lucybriant nathanmeister gerryblair matthewchamberlain paulyates wraywilson jamesgaylyn melvinlenoclarkiii carvonfutrell brandonjelkes micahmoch hanniyahmuhammad christophernolen christaoliver aprilmariethomas bravitaathreatt colinbleasdale mikebodnar mattclayton nicoledionne jamieharrison allanhenry anthonyingruber ashleyjeffery deanknowsley josephmikahunt terrynotary kaipantano loganpithyou stuartpollock raja garethruck rhiansheehan tjstorm jodietaylor aliciavelabailey richardwhiteside nikiezambo julenerenee jamescameron 22nd century paraplegic marine moon pandora unique mission becomes torn following order alien civilization dispatched protecting 2009 en
1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              adventure fantasy action ocean drugabuse exoticisland eastindiatradingcompany loveoneslife traitor shipwreck strongwoman ship alliance calypso afterlife fighter pirate swashbuckler aftercreditsstinger waltdisneypictures jerrybruckheimerfilms secondmateproductions johnnydepp orlandobloom keiraknightley stellanskarsgård chowyunfat billnighy geoffreyrush jackdavenport kevinmcnally tomhollander naomieharris jonathanpryce keithrichards leearenberg mackenziecrook gregellis davidbailie martinklebba davidschofield laurenmaher vanessabranch angusbarnett gilesnew reggielee dominicscottkay takayofischer davidmeunier hokwantse andybeckwith peterdonaldbadalamentiii christopherscapp keithrichards hakeemkaekazim ghassanmassoud goreverbinski captain barbossa long believed come back elizabeth swann dead life headed edge earth turner nothing quite seems 2007 en
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         action adventure crime spy basednovel secretagent sequel mi6 britishsecretservice unitedkingdom columbiapictures danjaq b24 danielcraig christophwaltz léaseydoux ralphfiennes monicabellucci benwhishaw naomieharris davebautista andrewscott rorykinnear jesperchristensen alessandrocremona stephaniesigman tenochhuerta adrianapaz domenicofortunato marcozingaro stefanoelfidiclaudia ianbonar tamwilliams richardbanham pipcarter simonlenagan alessandrobressanello marczinga brigittemillar adelbencherif gediminasadomaitis peppelanzetta francescoarca matteotaranto emilioaniba benitosagredo daitabuchi georgelasha sargonyelda andycheung erickhayden olegmirochnikov antoniosalines miloudmouradbenamara gidoschimanski nigelbarber patricenaiambana stephanecornicard garyfannin sadaoueda philliplaw waiwong josephbalderrama eijimihara junichikajioka victorschefé haraldwindisch tristanmatthiae detlefbothe bodofriesecke wilhemiben noemikrausz noahsaavedra francisattakpah michaelglantschnig marlonboess mariewohlmuth liliepply konstantingerlach laraparmiani umitulgen amramallassi ziadabaza walidmumuni derekhorsham nariblairmangat michaelwhite adammcgrady naderdernaika pezhmaanalinia judidench nevegachev karlfarrer kimadis maurisaselenecoleman matijamondimatović sammendes bond terrible truth behind spectre battle political force secret service alive peel back cryptic message ’ past sends sinister organization trail uncover keep layer deceit reveal 2015 en
3    action crime drama thriller dccomics crimefighter terrorist secretidentity burglar hostagedrama timebomb gothamcity vigilante coverup superhero villainess tragichero terrorism destruction catwoman catburglar imax flood criminalunderworld batman legendarypictures warnerbros dcentertainment syncopy christianbale michaelcaine garyoldman annehathaway tomhardy marioncotillard josephgordonlevitt morganfreeman cillianmurphy junotemple liamneeson matthewmodine alonaboutboul benmendelsohn nestorcarbonell joshpence tomconti joeyking warrenbrown danielsunjata samkennard aliashtepina nickjulian mirandanolan clairejulien aidangillen burngorman brettcullen reggielee josephlyletaylor chrisellis duanehenry jamesharveyward gonzalomenendez cameronjack lexdaniel tylerdeanflores thomaslennon trevorwhite robbrown fredriclehne courtneymunch chrishill travisguba jaybenedict willestes daviddayanfisher glenpowell russfega andresperezmolina brentbriscoe johnnolan olivercotton markkilleen sarahgoldberg johnmacmillan robertwisdom ronniegeneblevins johnhollingworth ianbohen urigavriel noelgugliemi hectoratreyuruiz patrickcox aramisknight joshstewart williamdevane davidgyasi patrickjordan joshuaelijahreese desmondharrington mychaelbates tomasarana peterholden davidmonahan jillianarmenante ajaevans aldousdavidson wadewilliams jakecanuso massifurlan christopherjudge patrickleahy toddgearhart marcabbink isiahadams charliealejandro robertarensen grantbabbitt fileenabahris rickbolander kylepatrickbrennan scottchurchson billcowher grahamcurry stephaniedominiehlert johnfarrer frankfata christopherbryangomez vitograssi michaelwrengucciardo samharris edheavey johnwiwanonkiw cindyjackson danieljordano williamkania tiffanykemp sunjaekim hrvojeklecz alexkruz tylerlamarr lejon pauljudeletersky joelipari silvialombardo jorgemardel calemcconnell daviddalemccue tiffanysandermckenzie allenmerritt olanmontgomery alexmoore shanenolan jacksonnunn josephobrien michaelpapajohn salomonpassariello kyledavidpierce troypolamalu michaelpower jamesrawlings kirstenroeters benroethlisberger markroman anthonyjsacco ericsalazar emilyschooley thomastull chrisvaina vincentvanommen michellevezzani barbaravincent justinmichaelwoods jasonyee mariazambrana johnzion alexziwak tommybayiokos matthewgooley jeffmoffitt markfalvo diogohausen garysievers orionmccabe londonmay jamesquinn danielnewman christophernolan attorney gotham dent batman city district harvey police department assumes responsibility eight year later mysterious selina kyle new terrorist leader dark knight resurfaces protect late subsequently hunted encounter villainous bane 2012 en
4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             action adventure sciencefiction basednovel mars medallion spacetravel princess alien steampunk martian escape edgarriceburroughs alienrace superhumanstrength marscivilization swordplanet 19thcentury 3d waltdisneypictures taylorkitsch lynncollins samanthamorton willemdafoe thomashadenchurch markstrong ciaránhinds dominicwest jamespurefoy bryancranston pollywalker darylsabara arkiereece davoodghadami pippanixon jamesembree philipphilmar emilytierney edmundkente nicholaswoodeson kyleagnew donstark joshdaugherty jaredcyr christophergoodman amandaclayton josephbillingiere andrewstanton carter former military captain reluctantly becomes embroiled john inexplicably transported exotic planet barsoom epic conflict rediscovers people rest war weary mysterious mar world brink collapse humanity realizes survival hand 2012 en
dtype: object

In [ ]:
# feed into the vectorizer

tfidf_matrix = tf.fit_transform(merge)
tfidf_matrix

<4803x84893 sparse matrix of type '<class 'numpy.float64'>'
	with 288922 stored elements in Compressed Sparse Row format>

## Distance Function

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity


cosine_similarities = cosine_similarity(tfidf_matrix)

In [ ]:
cosine_similarities.shape

(4803, 4803)

In [ ]:
clean1_df.set_index('title', inplace = True)

In [ ]:
movie_indices = pd.Series(clean1_df.index)

## Creating the Movie Recommender

In [ ]:
def get_movie_recommendation(name, cosine_similarities=cosine_similarities):
    
    recommended_movies = []
    
    # Get index of the movie that matches the name
    movie_index = movie_indices[movie_indices == name].index[0]

    # Create a Series with the similarity scores in descending order
    score_series = pd.Series(cosine_similarities[movie_index]).sort_values(ascending = False)

    # Get the indexes of the 5 most similar movies except itself
    top_indexes = list(score_series.iloc[1:6].index)
    
    # Populate the list with the names of the top 5 matching hotels
    for i in top_indexes:
        recommended_movies.append(list(clean1_df.index)[i])

    return recommended_movies

## Testing the Recommender

In [ ]:
get_movie_recommendation('The Dark Knight')

['Batman Returns',
 'Batman Begins',
 'The Dark Knight Rises',
 'Batman',
 'Batman: The Dark Knight Returns, Part 2']

In [ ]:
get_movie_recommendation('The Shawshank Redemption')

['The Green Mile', 'The Majestic', 'The Mist', 'Pulp Fiction', 'Mean Streets']

In [ ]:
get_movie_recommendation('Frozen')

['Wreck-It Ralph',
 'Big Hero 6',
 'Enchanted',
 'The Princess and the Frog',
 'Mr. Peabody & Sherman']